// Mimic Hunt — LOT 1 en projet (2026-09-18) : 16 items du palier I « Synonyms », mh13 à mh28.
// Même format que src/data/mimicHunt.js. PAS dans le jeu tant que Jérémy ne l'a pas relu :
//   relecture  → /prototypes/mimic-hunt/review.html (serveur Vite du dépôt, port 5608)
//   en partie  → /prototypes/mimic-hunt/real.html?lot=1 (vrai module, banque + ce lot)
//   contrôle   → node tests/check_mimic_items.cjs prototypes/mimic-hunt/drafts/lot1.js
//
// Rédaction : bonne réponse 4 fois en A, B, C et D ; 2 Mimics par item sauf mh21 (un seul) ;
// deux items gardent un mot sans synonyme courant dans la bonne réponse (mh18 « meeting », mh22
// « password ») ; les pièges citent l'option, jamais une lettre (les options sont permutées).
export var LOT = [
  {
    id: "mh13", tier: 1, ctx: "Email from HR",
    src: "All staff are required to complete the online safety training by the end of the month.",
    q: "What are employees asked to do?",
    opts: ["Train new staff online by the end of the month", "Finish a course before the deadline", "Report safety problems online", "Update their personal information"],
    c: 1,
    bridge: [["complete", "Finish"], ["training", "course"]],
    mimics: { 0: ["staff", "online", ["training", "Train"], "end of the month"], 2: ["safety", "online"] },
    exp: "Complete = finish, and the online safety training is a course. The date simply becomes 'the deadline'.",
    trap: "'Train new staff online…' reuses 'staff', 'online', 'training' and 'end of the month', but nobody is training anyone. 'Report safety problems online' keeps 'safety' and 'online' and invents a task.",
  },
  {
    id: "mh14", tier: 1, ctx: "Notice",
    src: "The staff cafeteria will be closed for renovations until further notice.",
    q: "What is stated about the cafeteria?",
    opts: ["It will be closed for a staff meeting.", "A new notice will be posted soon.", "It is being remodeled.", "It will offer a new menu."],
    c: 2,
    bridge: [["renovations", "remodeled"]],
    mimics: { 0: ["closed", "staff"], 1: ["notice"] },
    exp: "Renovations = remodeling work: the cafeteria is closed because it is being remodeled. 'Until further notice' just means no reopening date has been set.",
    trap: "'Closed for a staff meeting' keeps 'closed' and 'staff' but invents the reason. 'A new notice will be posted' takes 'notice' literally: in 'until further notice' it isn't a document.",
  },
  {
    id: "mh15", tier: 1, ctx: "Job posting",
    src: "The successful candidate will be responsible for managing a team of six sales representatives.",
    q: "What will the new employee do?",
    opts: ["Travel to meet international clients", "Hire six new sales representatives", "Manage the company's sales budget", "Supervise a group of salespeople"],
    c: 3,
    bridge: [["managing", "Supervise"], ["team", "group"], ["sales representatives", "salespeople"]],
    mimics: { 1: ["six", "sales representatives"], 2: [["managing", "Manage"], "sales"] },
    exp: "Managing a team = supervising a group, and sales representatives are salespeople.",
    trap: "'Hire six new sales representatives' copies 'six' and 'sales representatives', but hiring isn't managing. 'Manage the company's sales budget' keeps 'manage' and 'sales' and swaps people for money.",
  },
  {
    id: "mh16", tier: 1, ctx: "Voicemail",
    src: "Hi, this is Tom from Brightline Dental. I'm calling to let you know that your appointment has been moved to Thursday morning.",
    q: "Why is the speaker calling?",
    opts: ["To say that a visit has been rescheduled", "To say that the dental office has moved", "To ask the listener to call back on Thursday", "To request a payment"],
    c: 0,
    bridge: [["appointment", "visit"], ["moved", "rescheduled"]],
    mimics: { 1: ["dental", "moved"], 2: [["calling", "call"], "Thursday"] },
    exp: "The appointment is the visit, and 'moved to Thursday morning' means it was rescheduled.",
    trap: "'The dental office has moved' copies 'dental' and 'moved', but it's the appointment that moved, not the office. 'Call back on Thursday' reuses 'call' and 'Thursday' for a request Tom never makes.",
  },
  {
    id: "mh17", tier: 1, ctx: "Advertisement",
    src: "Sign up for our newsletter and receive a 10% discount on your first purchase.",
    q: "What is being offered?",
    opts: ["A free newsletter for first-time visitors", "Free delivery on large orders", "Money off an initial order", "10% of every purchase given to charity"],
    c: 2,
    bridge: [["discount", "Money off"], ["first purchase", "initial order"]],
    mimics: { 0: ["newsletter", ["first", "first-time"]], 3: ["10%", "purchase"] },
    exp: "A discount is money off, and your first purchase is an initial order.",
    trap: "'A free newsletter for first-time visitors' recycles 'newsletter' and 'first'. '10% of every purchase given to charity' keeps '10%' and 'purchase' and changes who gets the money.",
  },
  {
    id: "mh18", tier: 1, ctx: "Text message from Rachel",
    src: "Running about 15 minutes late. The train is delayed. Please start the meeting without me.",
    q: "What does Rachel ask her colleague to do?",
    opts: ["Delay the meeting by 15 minutes", "Book a conference room", "Take a later train", "Begin the meeting before she arrives"],
    c: 3,
    bridge: [["start", "Begin"], ["without me", "before she arrives"]],
    echo: ["meeting"],
    mimics: { 0: [["delayed", "Delay"], "meeting", "15 minutes"], 2: ["train", ["late", "later"]] },
    exp: "Start = begin, and 'without me' means before she gets there. 'Meeting' stays: it has no everyday synonym here.",
    trap: "'Delay the meeting by 15 minutes' turns 'delayed' and '15 minutes' into the opposite request. 'Take a later train' reuses 'train' and 'late', but Rachel is the one on the train.",
  },
  {
    id: "mh19", tier: 1, ctx: "Memo",
    src: "Please note that the parking garage will be inaccessible on Saturday due to maintenance work.",
    q: "What does the memo say about the parking garage?",
    opts: ["It will be closed this weekend.", "Parking there will be free on Saturday.", "Maintenance workers will park there.", "Its prices will increase next month."],
    c: 0,
    bridge: [["inaccessible", "closed"], ["Saturday", "this weekend"]],
    mimics: { 1: ["parking", "Saturday"], 2: ["maintenance", ["parking", "park"]] },
    exp: "Inaccessible = closed (nobody can get in), and Saturday becomes 'this weekend'.",
    trap: "'Parking there will be free on Saturday' copies 'parking' and 'Saturday' and invents a price. 'Maintenance workers will park there' reuses 'maintenance' and 'park', but the workers are fixing the garage, not using it.",
  },
  {
    id: "mh20", tier: 1, ctx: "Email from a client",
    src: "Could you send me an estimate for printing 500 brochures?",
    q: "What does the client want?",
    opts: ["An estimate of how long the printing will take", "A price quote for a print job", "A meeting to discuss a design", "500 brochures sent by email"],
    c: 1,
    bridge: [["estimate", "price quote"], ["printing", "print job"]],
    mimics: { 0: ["estimate", "printing"], 3: ["500 brochures", ["send", "sent"]] },
    exp: "An estimate for a job is a price quote, and printing brochures is a print job.",
    trap: "'An estimate of how long the printing will take' keeps 'estimate' and 'printing', but the client asks about cost, not time. '500 brochures sent by email' reuses '500 brochures' and 'send' for a delivery nobody requested.",
  },
  {
    id: "mh21", tier: 1, ctx: "Product label",
    src: "Store in a cool, dry place and keep out of reach of children.",
    q: "What does the label advise?",
    opts: ["Take it with a meal", "Keep the product away from heat and moisture", "Place it where children can reach it easily", "Throw it away after one month"],
    c: 1,
    bridge: [["cool, dry place", "away from heat and moisture"]],
    mimics: { 2: ["place", "children", "reach"] },
    exp: "A cool, dry place means away from heat and moisture. Same advice, different words.",
    trap: "'Place it where children can reach it easily' reuses 'place', 'children' and 'reach' to say the exact opposite of the label.",
  },
  {
    id: "mh22", tier: 1, ctx: "Email from IT Support",
    src: "Your password will expire in three days. Please update it to keep access to your account.",
    q: "What is the recipient asked to do?",
    opts: ["Update their account details", "Contact the help desk", "Wait three days before logging in", "Change their password soon"],
    c: 3,
    bridge: [["update", "Change"], ["in three days", "soon"]],
    echo: ["password"],
    mimics: { 0: ["update", "account"], 2: ["three days"] },
    exp: "Update = change, and 'in three days' means soon. 'Password' stays: there's no everyday synonym.",
    trap: "'Update their account details' keeps 'update' and 'account' but changes what must be updated. 'Wait three days before logging in' copies 'three days' and turns a deadline into a waiting time.",
  },
  {
    id: "mh23", tier: 1, ctx: "Conversation", speaker: "Man",
    src: "I'm afraid we've run out of the blue folders, but we have plenty of green ones.",
    q: "What does the man say about the blue folders?",
    opts: ["There are plenty of them.", "They are sold out.", "They cost more than the green ones.", "They will arrive tomorrow."],
    c: 1,
    bridge: [["run out of", "sold out"]],
    mimics: { 0: ["plenty"], 2: ["green ones"] },
    exp: "Run out of = have none left, like 'sold out'. The blue folders are gone; only the green ones remain.",
    trap: "'There are plenty of them' grabs 'plenty', but that describes the green folders. 'They cost more than the green ones' copies 'green ones' and invents a price.",
  },
  {
    id: "mh24", tier: 1, ctx: "Hotel notice",
    src: "Complimentary breakfast is served in the lobby from 6:30 to 10:00 a.m.",
    q: "What is offered to guests?",
    opts: ["A free morning meal", "Late check-out until 10:00 a.m.", "Room service in the lobby", "A shuttle to the airport"],
    c: 0,
    bridge: [["Complimentary", "free"], ["breakfast", "morning meal"]],
    mimics: { 1: ["10:00 a.m."], 2: ["lobby", ["served", "service"]] },
    exp: "Complimentary = free, and breakfast is the morning meal.",
    trap: "'Late check-out until 10:00 a.m.' copies the time but offers something else. 'Room service in the lobby' reuses 'lobby' and turns 'served' into 'service'.",
  },
  {
    id: "mh25", tier: 1, ctx: "Email from a manager",
    src: "I'd like to thank everyone for their hard work on the Henderson project.",
    q: "Why did the manager write the email?",
    opts: ["To ask everyone to work harder", "To announce a new client", "To assign more work on the Henderson project", "To express appreciation to the team"],
    c: 3,
    bridge: [["thank", "express appreciation"], ["everyone", "the team"]],
    mimics: { 0: ["everyone", "work", ["hard", "harder"]], 2: ["work", "Henderson project"] },
    exp: "To thank everyone = to express appreciation to the team.",
    trap: "'To ask everyone to work harder' recycles 'everyone', 'hard' and 'work' into a complaint. 'To assign more work on the Henderson project' keeps the project's name, but the manager is thanking, not assigning.",
  },
  {
    id: "mh26", tier: 1, ctx: "Store announcement",
    src: "Our store will stay open later than usual throughout the holiday season.",
    q: "What is being announced?",
    opts: ["The store will close for the holiday season", "Discounts on seasonal items", "Extended opening hours this festive period", "Employees must stay later than usual"],
    c: 2,
    bridge: [["stay open later", "Extended opening hours"], ["holiday season", "festive period"]],
    mimics: { 0: ["store", "holiday season"], 3: ["stay", "later than usual"] },
    exp: "Staying open later = extended opening hours, and the holiday season is the festive period.",
    trap: "'The store will close for the holiday season' keeps 'store' and 'holiday season' but says the opposite. 'Employees must stay later than usual' copies 'stay' and 'later than usual', but it's the store that stays open; nothing is said about staff.",
  },
  {
    id: "mh27", tier: 1, ctx: "Email from a supplier",
    src: "Unfortunately, the item you ordered is currently out of stock.",
    q: "What problem does the supplier mention?",
    opts: ["A product is unavailable right now.", "The company's stock price has fallen.", "A payment was declined.", "The order was sent to the wrong address."],
    c: 0,
    bridge: [["item", "product"], ["out of stock", "unavailable"], ["currently", "right now"]],
    mimics: { 1: ["stock"], 3: [["ordered", "order"]] },
    exp: "Out of stock = unavailable, the item is the product, and currently = right now.",
    trap: "'The company's stock price has fallen' takes 'stock' in the wrong sense: here it means goods in the warehouse, not shares. 'The order was sent to the wrong address' reuses 'order' for a problem the email never mentions.",
  },
  {
    id: "mh28", tier: 1, ctx: "Conversation", speaker: "Woman",
    src: "Could you give me a hand moving these boxes to the storage room?",
    q: "What does the woman ask for?",
    opts: ["A larger storage room", "A list of office supplies", "Some help carrying items", "Permission to move to a different room"],
    c: 2,
    bridge: [["give me a hand", "help"], ["moving these boxes", "carrying items"]],
    mimics: { 0: ["storage room"], 3: [["moving", "move"], "room"] },
    exp: "Give me a hand = help me, and moving boxes means carrying items.",
    trap: "'A larger storage room' copies 'storage room', and 'Permission to move to a different room' turns 'moving' and 'room' into a new request. Neither is what she asks for.",
  },
];
