// Mimic Hunt — LOT 2 en projet (2026-09-19) : 16 items du palier II « Reshaped », mh29 à mh44.
// Même format que src/data/mimicHunt.js, HORS jeu tant que Jérémy ne l'a pas relu (voir lot1.js pour
// la relecture, le banc et le contrôle).
//
// Le palier II change la FORME, pas seulement les mots : actif ↔ passif (mh35, mh38), négation ↔
// affirmation (mh29, mh39, mh41, mh44), comparaison retournée (mh30, mh44), condition → exigence (mh32,
// mh34, mh42), proposition → nom (mh31, mh40, mh43), ordre du temps (mh37), cause déplacée (mh33, mh36).
// Plusieurs Mimics recopient PRESQUE tout et ne changent qu'un rôle ou une négation (mh38, mh44) : c'est
// le piège propre à ce palier. Bonne réponse 4 fois en A, B, C et D ; un seul Mimic en mh40 ; mh35 garde
// un nom propre dans la bonne réponse.
export var LOT = [
  {
    id: "mh29", tier: 2, ctx: "Notice",
    src: "Only employees with a valid badge may enter the server room.",
    q: "What is stated about the server room?",
    opts: ["A valid badge can be picked up in the server room.", "People without a badge are not allowed in.", "It is being renovated this week.", "Employees must enter it in pairs."],
    c: 1,
    bridge: [["Only employees with a valid badge may enter", "People without a badge are not allowed in"]],
    mimics: { 0: ["valid badge", "server room"], 3: ["employees", "enter"] },
    exp: "'Only employees with a badge may enter' becomes a negative: without a badge, you can't go in. Same rule, turned around.",
    trap: "'A valid badge can be picked up in the server room' copies 'valid badge' and 'server room' and invents a place to collect badges. 'Employees must enter it in pairs' keeps 'employees' and 'enter' but adds a rule the notice never gives.",
  },
  {
    id: "mh30", tier: 2, ctx: "Email from a supplier",
    src: "Our new cartridges cost less than the old ones and last twice as long.",
    q: "What is suggested about the old cartridges?",
    opts: ["They last twice as long.", "They are no longer being sold.", "They were more expensive.", "They cost less than the new ones."],
    c: 2,
    bridge: [["cost less than", "more expensive"]],
    mimics: { 0: ["last twice as long"], 3: ["cost less than", ["new cartridges", "new ones"]] },
    exp: "If the new ones cost less, the old ones cost more. The comparison is turned around; the meaning stays.",
    trap: "'They last twice as long' and 'They cost less than the new ones' both copy real phrases from the email, but those phrases describe the new cartridges, not the old ones.",
  },
  {
    id: "mh31", tier: 2, ctx: "Memo",
    src: "We have decided to postpone the product launch because the packaging is not ready.",
    q: "Why was the launch postponed?",
    opts: ["Because of a lack of funding", "Because the product is not ready", "Because the product needs new packaging", "Because of a delay with the boxes"],
    c: 3,
    bridge: [["packaging", "boxes"], ["is not ready", "delay"]],
    mimics: { 1: ["product", "is not ready"], 2: ["product", "packaging"] },
    exp: "'The packaging is not ready' becomes 'a delay with the boxes': the clause turns into a noun, and packaging = boxes.",
    trap: "'Because the product is not ready' copies 'product' and 'is not ready', but it's the packaging that isn't ready. 'Because the product needs new packaging' reuses 'product' and 'packaging' and invents a redesign.",
  },
  {
    id: "mh32", tier: 2, ctx: "Store policy",
    src: "Refunds will not be issued unless the item is returned with its receipt.",
    q: "What is required to get a refund?",
    opts: ["Refunds are issued without a receipt.", "Customers must pay a small fee.", "Customers need to show proof of purchase.", "The item must be returned unused."],
    c: 2,
    bridge: [["unless", "need to"], ["receipt", "proof of purchase"]],
    mimics: { 0: ["refunds", "issued", "receipt"], 3: ["item", "returned"] },
    exp: "'No refund unless you bring the receipt' means you need the receipt, and a receipt is proof of purchase. The negative condition becomes a requirement.",
    trap: "'Refunds are issued without a receipt' copies 'refunds', 'issued' and 'receipt' to say the opposite. 'The item must be returned unused' keeps 'item' and 'returned' and adds a condition the policy doesn't set.",
  },
  {
    id: "mh33", tier: 2, ctx: "Email from the organizers",
    src: "Because of the heavy snow, the conference has been moved online.",
    q: "What is indicated about the conference?",
    opts: ["It has been moved to a bigger venue.", "It will take place virtually due to the weather.", "It has been canceled.", "Heavy traffic is expected at the conference."],
    c: 1,
    bridge: [["moved online", "take place virtually"], ["heavy snow", "weather"]],
    mimics: { 0: ["has been moved"], 3: ["heavy", "conference"] },
    exp: "'Moved online' = takes place virtually, and heavy snow is the weather. The cause moves from the start of the sentence to the end.",
    trap: "'It has been moved to a bigger venue' keeps 'has been moved' but invents a new place. 'Heavy traffic is expected at the conference' recycles 'heavy' and 'conference' into a problem the email never mentions.",
  },
  {
    id: "mh34", tier: 2, ctx: "Conversation", speaker: "Woman",
    src: "I don't think we'll finish the report unless someone helps us with the charts.",
    q: "What does the woman suggest?",
    opts: ["They need an extra person for the graphs.", "Someone has already finished the charts.", "They should leave early today.", "The report does not need any charts."],
    c: 0,
    bridge: [["someone helps us", "an extra person"], ["charts", "graphs"]],
    mimics: { 1: ["someone", ["finish", "finished"], "charts"], 3: ["report", "charts"] },
    exp: "'We won't finish unless someone helps' means they need help: one more person to do the charts, here called graphs.",
    trap: "'Someone has already finished the charts' reuses 'someone', 'finish' and 'charts' to say the job is done, the opposite. 'The report does not need any charts' keeps 'report' and 'charts' but says something she never says.",
  },
  {
    id: "mh35", tier: 2, ctx: "Press release",
    src: "Harper Foods announced yesterday that it will open three new stores in Denver.",
    q: "What did Harper Foods announce?",
    opts: ["It opened three stores yesterday.", "It is looking for new suppliers.", "It is moving its headquarters to Denver.", "Three locations are going to be opened in Denver."],
    c: 3,
    bridge: [["will open three new stores", "Three locations are going to be opened"]],
    echo: ["Denver"],
    mimics: { 0: [["open", "opened"], "three", "stores", "yesterday"], 2: ["Denver"] },
    exp: "'It will open three new stores' becomes 'three locations are going to be opened': active becomes passive, stores become locations. Denver stays: it's a name.",
    trap: "'It opened three stores yesterday' copies 'open', 'three', 'stores' and 'yesterday', but yesterday is when the news came out, not when the stores opened. 'It is moving its headquarters to Denver' reuses the city for a different plan.",
  },
  {
    id: "mh36", tier: 2, ctx: "Email from a colleague",
    src: "The file is too large to send as an attachment, so I've uploaded it to the shared drive.",
    q: "Why didn't the writer attach the file?",
    opts: ["The attachment could not be uploaded.", "It exceeded the size limit.", "The file contained a virus.", "The shared drive was too large."],
    c: 1,
    bridge: [["too large to send", "exceeded the size limit"]],
    mimics: { 0: ["attachment", "uploaded"], 3: ["shared drive", "too large"] },
    exp: "'Too large to send' means it went over the limit: the adjective becomes a verb and a noun.",
    trap: "'The attachment could not be uploaded' mixes 'attachment' and 'uploaded', but the upload worked. 'The shared drive was too large' moves 'too large' from the file to the drive.",
  },
  {
    id: "mh37", tier: 2, ctx: "Voicemail",
    src: "Before you come to the office, please call me so I can meet you at the entrance.",
    q: "What is the listener asked to do?",
    opts: ["Come to the office before calling", "Phone ahead of arriving", "Bring a form of identification", "Wait at the office entrance"],
    c: 1,
    bridge: [["call me", "Phone"], ["Before you come", "ahead of arriving"]],
    mimics: { 0: ["come to the office", ["call", "calling"], "before"], 3: ["office", "entrance"] },
    exp: "'Before you come, call me' = phone ahead of arriving. The 'before' clause becomes 'ahead of'.",
    trap: "'Come to the office before calling' copies 'come to the office', 'before' and 'call' but swaps the order: the call comes first. 'Wait at the office entrance' reuses 'office' and 'entrance', but the speaker is the one who will be waiting.",
  },
  {
    id: "mh38", tier: 2, ctx: "Local news",
    src: "The award was presented to Ms. Tanaka by the mayor.",
    q: "What happened at the ceremony?",
    opts: ["The mayor gave Ms. Tanaka a prize.", "Ms. Tanaka presented an award to the mayor.", "The ceremony was postponed.", "The mayor received an award."],
    c: 0,
    bridge: [["was presented to Ms. Tanaka by the mayor", "The mayor gave Ms. Tanaka"], ["award", "prize"]],
    mimics: { 1: ["Ms. Tanaka", "presented", "award", "mayor"], 3: ["mayor", "award"] },
    exp: "In 'was presented to Ms. Tanaka by the mayor', the mayor is the one giving. Passive becomes active: the mayor gave her a prize (award = prize).",
    trap: "'Ms. Tanaka presented an award to the mayor' and 'The mayor received an award' keep the names and the words but swap who gives and who receives. A passive sentence puts the doer at the end: read 'by the mayor' carefully.",
  },
  {
    id: "mh39", tier: 2, ctx: "Email from a hotel",
    src: "Unfortunately, no rooms are available on the dates you requested.",
    q: "What does the hotel tell the customer?",
    opts: ["Room rates have changed for those dates.", "Breakfast is no longer included.", "The customer requested the wrong dates.", "It is fully booked for those days."],
    c: 3,
    bridge: [["no rooms are available", "fully booked"], ["dates you requested", "those days"]],
    mimics: { 0: [["rooms", "Room"], "dates"], 2: ["requested", "dates"] },
    exp: "'No rooms are available' = fully booked: the negative becomes one positive expression. The dates you requested = those days.",
    trap: "'Room rates have changed for those dates' reuses 'room' and 'dates' for a price change. 'The customer requested the wrong dates' keeps 'requested' and 'dates' and blames the customer, which the email never does.",
  },
  {
    id: "mh40", tier: 2, ctx: "Memo",
    src: "The renovation of the lobby will cause some noise next week.",
    q: "What does the memo warn about?",
    opts: ["The lobby will be closed next week.", "A new receptionist will start soon.", "It will be loud while the entrance is being redone.", "Parking fees will go up."],
    c: 2,
    bridge: [["noise", "loud"], ["renovation of the lobby", "the entrance is being redone"]],
    mimics: { 0: ["lobby", "next week"] },
    exp: "'The renovation of the lobby' becomes a whole clause, 'while the entrance is being redone', and 'noise' becomes 'loud'.",
    trap: "'The lobby will be closed next week' keeps 'lobby' and 'next week', but the memo warns about noise, not a closure.",
  },
  {
    id: "mh41", tier: 2, ctx: "Company policy",
    src: "Employees may not use company phones for personal calls.",
    q: "What does the policy say?",
    opts: ["The company will pay for personal calls.", "Meetings must start on time.", "Employees may use their own phones at work.", "Work phones are for business only."],
    c: 3,
    bridge: [["company phones", "Work phones"], ["may not use", "for business only"]],
    mimics: { 0: ["company", "personal calls"], 2: ["employees", "use"] },
    exp: "'May not use for personal calls' = for business only. A ban turns into a restriction.",
    trap: "'The company will pay for personal calls' reuses 'company' and 'personal calls' and reverses the rule. 'Employees may use their own phones at work' keeps 'employees' and 'use' but talks about personal phones, which the policy doesn't cover.",
  },
  {
    id: "mh42", tier: 2, ctx: "Conversation", speaker: "Man",
    src: "If the client doesn't sign by Friday, we'll lose the deal.",
    q: "What does the man say?",
    opts: ["The client will sign on Friday.", "They have already lost the deal.", "The agreement depends on a signature before the weekend.", "The price will go up next month."],
    c: 2,
    bridge: [["deal", "agreement"], ["sign by Friday", "signature before the weekend"]],
    mimics: { 0: ["client", "sign", "Friday"], 1: [["lose", "lost"], "deal"] },
    exp: "'If the client doesn't sign by Friday, we'll lose the deal' means the agreement depends on a signature before the weekend. The 'if' clause becomes a noun: signature.",
    trap: "'The client will sign on Friday' keeps 'client', 'sign' and 'Friday' but turns a risk into a promise. 'They have already lost the deal' reuses 'lose' and 'deal', but the loss hasn't happened.",
  },
  {
    id: "mh43", tier: 2, ctx: "Email from Accounts Payable",
    src: "The invoice you sent us last week was paid in full on Tuesday.",
    q: "What does the writer say about the invoice?",
    opts: ["The entire amount has been settled.", "Only part of it was paid.", "It was sent last Tuesday.", "It contained a mistake."],
    c: 0,
    bridge: [["paid in full", "entire amount has been settled"]],
    mimics: { 1: ["paid"], 2: ["sent", "Tuesday"] },
    exp: "'Paid in full' = the entire amount has been settled: the same fact, told with a different verb and structure.",
    trap: "'Only part of it was paid' keeps 'paid' and drops 'in full', which flips the meaning. 'It was sent last Tuesday' mixes the two dates: it was sent last week and paid on Tuesday.",
  },
  {
    id: "mh44", tier: 2, ctx: "Product review",
    src: "The new model is not as heavy as the previous one.",
    q: "What is said about the new model?",
    opts: ["It is lighter than the older version.", "It comes in several colors.", "It is the heaviest model yet.", "It is as heavy as the previous one."],
    c: 0,
    bridge: [["not as heavy as", "lighter than"], ["previous one", "older version"]],
    mimics: { 2: [["heavy", "heaviest"], "model"], 3: ["as heavy as", "previous one"] },
    exp: "'Not as heavy as' = lighter than. The negative comparison becomes a positive one, and the previous one is the older version.",
    trap: "'It is as heavy as the previous one' copies nearly everything but drops 'not', which reverses the meaning. 'It is the heaviest model yet' turns 'heavy' into a superlative the review never uses.",
  },
];
