// Mimic Hunt — LOT 3 en projet (2026-09-19) : 16 items du palier III « Big picture », mh45 à mh60.
// Même format que src/data/mimicHunt.js, HORS jeu tant que Jérémy ne l'a pas relu (voir lot1.js pour
// la relecture, le banc et le contrôle).
//
// Le palier III fait prendre du recul : des détails deviennent une catégorie (mh48, mh60), une liste de
// tâches devient un métier (mh55), des indices désignent un lieu (mh46, mh50) ou une activité (mh52), et
// les questions de but, de sujet ou d'intention demandent l'idée d'ensemble (mh47, mh49, mh51, mh53, mh56,
// mh58, mh59), comme au vrai test (Parts 3, 4 et 7). Bonne réponse 4 fois en A, B, C et D ; un seul Mimic
// en mh50 ; mh59 garde « subscription » dans la bonne réponse (pas de synonyme courant), comme mh12.
export var LOT = [
  {
    id: "mh45", tier: 3, ctx: "Conversation", speaker: "Man",
    src: "Could you print twenty copies of the agenda and put them on the conference table before ten?",
    q: "What does the man ask the woman to do?",
    opts: ["Book the conference room for ten people", "Prepare materials for a meeting", "Put the agenda on the company website", "Order lunch for the team"],
    c: 1,
    bridge: [["print twenty copies of the agenda", "Prepare materials"], ["conference table", "meeting"]],
    mimics: { 0: ["conference", "ten"], 2: ["put", "agenda"] },
    exp: "Printing copies of the agenda and setting them on the conference table is preparing materials for a meeting. The answer names the task, not the details.",
    trap: "'Book the conference room for ten people' recycles 'conference' and 'ten' (the time becomes a headcount). 'Put the agenda on the company website' keeps 'put' and 'agenda' but moves it online.",
  },
  {
    id: "mh46", tier: 3, ctx: "Announcement",
    src: "Passengers on Flight 208 to Oslo are invited to proceed to Gate 14, where boarding will begin shortly.",
    q: "Where is this announcement most likely being made?",
    opts: ["At a train station", "In the city of Oslo", "On board the plane", "In an airport terminal"],
    c: 3,
    bridge: [["Flight 208", "airport"], ["Gate 14", "terminal"]],
    mimics: { 1: ["Oslo"], 2: [["boarding", "board"]] },
    exp: "A flight number, a gate and boarding: together they point to an airport terminal. The answer is the place the details add up to.",
    trap: "'In the city of Oslo' copies the destination, not the place where the announcement is made. 'On board the plane' borrows 'board' from 'boarding', which hasn't started yet.",
  },
  {
    id: "mh47", tier: 3, ctx: "Email to the team",
    src: "Attached are the photos from Saturday's team-building day. Thanks to everyone who came, and let's do it again in the spring!",
    q: "What is the main purpose of the email?",
    opts: ["To share images from a company event", "To schedule a team-building day for Saturday", "To request feedback on a training course", "To invite staff to a spring party"],
    c: 0,
    bridge: [["photos", "images"], ["team-building day", "company event"], ["Attached are", "share"]],
    mimics: { 1: ["team-building day", "Saturday"], 3: ["spring"] },
    exp: "The photos are images, the team-building day is a company event, and 'attached are' means the writer is sharing them. The thanks and the spring idea are extras, not the purpose.",
    trap: "'To schedule a team-building day for Saturday' copies the event and the day, but it has already happened. 'To invite staff to a spring party' grabs 'spring' from a vague wish: no invitation is sent.",
  },
  {
    id: "mh48", tier: 3, ctx: "Conversation", speaker: "Woman",
    src: "The printer on the third floor is jammed again, and the copier downstairs is out of toner.",
    q: "What problem does the woman mention?",
    opts: ["The internet connection is slow.", "The third floor is closed.", "Office equipment is not working.", "They need a new printer downstairs."],
    c: 2,
    bridge: [["printer", "Office equipment"], ["jammed", "not working"]],
    mimics: { 1: ["third floor"], 3: ["printer", "downstairs"] },
    exp: "A jammed printer and a copier with no toner: two details, one category. Office equipment is not working.",
    trap: "'The third floor is closed' copies 'third floor', where the printer is. 'They need a new printer downstairs' mixes 'printer' and 'downstairs', but the printer is upstairs and nobody talks about buying one.",
  },
  {
    id: "mh49", tier: 3, ctx: "Voicemail",
    src: "Hi Ms. Park, this is Leo from Carter Realty. The owners accepted your offer on the house on Maple Street. Call me back so we can go over the next steps.",
    q: "Why is the speaker calling?",
    opts: ["To share good news about a purchase", "To make an offer on a house on Maple Street", "To ask for a rent payment", "To ask Ms. Park to call the owners"],
    c: 0,
    bridge: [["accepted your offer", "good news"], ["offer on the house", "purchase"]],
    mimics: { 1: ["offer", "house", "Maple Street"], 3: ["call", "owners"] },
    exp: "The owners said yes to her offer: that's good news about the house she wants to buy. Purpose questions want the reason for the call, not the details.",
    trap: "'To make an offer on a house on Maple Street' copies 'offer', 'house' and 'Maple Street', but Ms. Park made the offer, not Leo. 'To ask Ms. Park to call the owners' reuses 'call' and 'owners': she has to call Leo back, not the owners.",
  },
  {
    id: "mh50", tier: 3, ctx: "Notice",
    src: "Please remember to label your food with your name and the date. Anything left in the fridge after Friday will be thrown away.",
    q: "Where would this notice most likely be posted?",
    opts: ["In a hotel lobby", "In a food store", "In a shared kitchen", "In a parking garage"],
    c: 2,
    bridge: [["fridge", "kitchen"], ["label your food with your name", "shared"]],
    mimics: { 1: ["food"] },
    exp: "Labeling your food and a fridge that is cleared every Friday: the details add up to a kitchen that several people share.",
    trap: "'In a food store' copies 'food', but a store doesn't ask customers to label their own food.",
  },
  {
    id: "mh51", tier: 3, ctx: "Email from a customer",
    src: "I ordered a blue jacket in size medium, but I received a black one in size large.",
    q: "Why did the customer write?",
    opts: ["To order a jacket in a larger size", "To ask about a delivery date", "To say that the black jacket fits well", "To complain about an incorrect order"],
    c: 3,
    bridge: [["received a black one in size large", "an incorrect order"]],
    mimics: { 0: ["jacket", ["ordered", "order"], ["large", "larger"]], 2: ["black", "jacket"] },
    exp: "Blue in medium ordered, black in large received: that's an incorrect order, and writing about it is a complaint.",
    trap: "'To order a jacket in a larger size' recycles 'order', 'jacket' and 'large' into a new purchase. 'To say that the black jacket fits well' keeps 'black' and 'jacket', but the customer got the wrong item and says nothing about the fit.",
  },
  {
    id: "mh52", tier: 3, ctx: "Conversation", speaker: "Man",
    src: "I've booked a table for six at Luigi's, and the taxi will pick us up at seven.",
    q: "What are the speakers most likely doing tonight?",
    opts: ["Buying a table for six people", "Going out for dinner", "Watching a movie at home", "Driving a taxi at seven"],
    c: 1,
    bridge: [["booked a table", "Going out"], ["Luigi's", "dinner"]],
    mimics: { 0: ["table", "six"], 3: ["taxi", "seven"] },
    exp: "A table booked at Luigi's and a taxi at seven: they're going out to a restaurant. The answer names the plan the details point to.",
    trap: "'Buying a table for six people' takes 'table' literally: booking a table means reserving it. 'Driving a taxi at seven' copies 'taxi' and 'seven', but the taxi is picking them up.",
  },
  {
    id: "mh53", tier: 3, ctx: "Business article",
    src: "After three years of falling sales, the bookstore chain has closed half of its shops and moved its focus to online orders.",
    q: "What is the article mainly about?",
    opts: ["A company changing its business strategy", "A bookstore that opened three new shops", "Falling prices for online books", "A new author's first novel"],
    c: 0,
    bridge: [["moved its focus to online orders", "changing its business strategy"], ["bookstore chain", "company"]],
    mimics: { 1: ["bookstore", "three", "shops"], 2: ["falling", "online"] },
    exp: "Closing shops and focusing on online orders is a change of business strategy, and a bookstore chain is a company. Main-idea questions want the whole story in a few words.",
    trap: "'A bookstore that opened three new shops' copies 'bookstore', 'three' and 'shops' and turns closures into openings. 'Falling prices for online books' keeps 'falling' and 'online', but it's sales that fell, not prices.",
  },
  {
    id: "mh54", tier: 3, ctx: "Chat message from Nina",
    src: "Traffic on the bridge is terrible. Start the presentation with the budget slides and I'll do the rest when I get there.",
    q: "What is implied about Nina?",
    opts: ["She will do the whole presentation.", "She is working from home today.", "She will arrive late.", "She prepared the budget slides."],
    c: 2,
    bridge: [["Traffic on the bridge is terrible", "arrive late"]],
    mimics: { 0: ["do", "presentation"], 3: ["budget slides"] },
    exp: "Terrible traffic and 'when I get there': Nina will be late. The answer is what the details imply, not a word taken from them.",
    trap: "'She will do the whole presentation' copies 'do' and 'presentation', but she asks the others to start without her. 'She prepared the budget slides' reuses 'budget slides', but nothing says who made them.",
  },
  {
    id: "mh55", tier: 3, ctx: "Job posting",
    src: "We are looking for someone who can answer calls, greet visitors and keep the front desk organized.",
    q: "What position is being advertised?",
    opts: ["A receptionist", "A call center manager", "An accountant", "A tour guide for visitors"],
    c: 0,
    bridge: [["answer calls, greet visitors", "A receptionist"]],
    mimics: { 1: [["calls", "call"]], 3: ["visitors"] },
    exp: "Answering calls, greeting visitors, keeping the front desk tidy: three tasks, one job title. That's a receptionist.",
    trap: "'A call center manager' borrows 'call' from 'answer calls', and 'A tour guide for visitors' takes 'visitors'. Each keeps one task and invents a different job.",
  },
  {
    id: "mh56", tier: 3, ctx: "Radio announcement",
    src: "Due to an accident on Highway 9, drivers heading downtown should expect delays of up to an hour.",
    q: "What is the purpose of the announcement?",
    opts: ["To advertise a new bus service", "To warn commuters about a traffic problem", "To announce the opening of Highway 9", "To report an accident that lasted an hour downtown"],
    c: 1,
    bridge: [["accident on Highway 9", "traffic problem"], ["drivers heading downtown", "commuters"], ["should expect", "warn"]],
    mimics: { 2: ["Highway 9"], 3: ["accident", "hour", "downtown"] },
    exp: "An accident and delays for drivers heading downtown: the purpose is to warn commuters about a traffic problem.",
    trap: "'To announce the opening of Highway 9' copies the road's name for news the announcement doesn't give. 'To report an accident that lasted an hour downtown' mixes 'accident', 'hour' and 'downtown': the hour is the delay, and the accident is on the highway.",
  },
  {
    id: "mh57", tier: 3, ctx: "Conversation", speaker: "Woman",
    src: "Could you check whether the hotel has a shuttle from the airport? My flight lands at midnight.",
    q: "What is the woman concerned about?",
    opts: ["The price of her hotel room", "Checking in to the hotel at midnight", "Getting transportation late at night", "Missing her flight to the airport"],
    c: 2,
    bridge: [["shuttle", "transportation"], ["midnight", "late at night"]],
    mimics: { 1: [["check", "Checking"], "hotel", "midnight"], 3: ["flight", "airport"] },
    exp: "She asks about a shuttle because she lands at midnight: her worry is getting a ride late at night. Shuttle = transportation.",
    trap: "'Checking in to the hotel at midnight' reuses 'check', 'hotel' and 'midnight', but she's asking someone to check something, not checking in. 'Missing her flight to the airport' copies 'flight' and 'airport', but her flight is arriving, not leaving.",
  },
  {
    id: "mh58", tier: 3, ctx: "Memo",
    src: "Starting next month, each team will have its own budget and will no longer need the finance department's approval for purchases under $500.",
    q: "What is the memo mainly about?",
    opts: ["A new $500 bonus for each team", "The opening of a new office", "Hiring for the finance department", "A change in how spending is approved"],
    c: 3,
    bridge: [["no longer need the finance department's approval", "change in how spending is approved"], ["purchases", "spending"]],
    mimics: { 0: ["$500", "each team"], 2: ["finance department"] },
    exp: "Teams get their own budget and small purchases no longer go through finance: the memo is about a new way of approving spending.",
    trap: "'A new $500 bonus for each team' copies '$500' and 'each team', but $500 is a spending limit, not a bonus. 'Hiring for the finance department' keeps the department's name and invents a job opening.",
  },
  {
    id: "mh59", tier: 3, ctx: "Email from a publisher",
    src: "Your subscription to Business Weekly will end on June 30. Renew now to keep receiving the magazine.",
    q: "Why was the email sent?",
    opts: ["To announce a new magazine", "To remind a reader that a subscription is ending", "To confirm a payment made on June 30", "To offer a job at a publishing company"],
    c: 1,
    bridge: [["will end on June 30", "is ending"]],
    echo: ["subscription"],
    mimics: { 0: ["magazine"], 2: ["June 30"] },
    exp: "The subscription ends on June 30 and the reader is asked to renew: it's a reminder. 'Subscription' stays in the answer: there's no everyday synonym.",
    trap: "A repeated word isn't always a trap: 'subscription' is in the right answer too. The Mimics are 'To announce a new magazine', which copies 'magazine' for news the email doesn't give, and 'To confirm a payment made on June 30', which turns the end date into a payment date.",
  },
  {
    id: "mh60", tier: 3, ctx: "Conversation", speaker: "Man",
    src: "The projector keeps turning off, so I'll give my presentation from the handouts instead.",
    q: "What problem does the man mention?",
    opts: ["His handouts are missing.", "The meeting room is too small.", "He has to turn off the lights for his presentation.", "A piece of equipment is unreliable."],
    c: 3,
    bridge: [["projector", "piece of equipment"], ["keeps turning off", "unreliable"]],
    mimics: { 0: ["handouts"], 2: [["turning off", "turn off"], "presentation"] },
    exp: "A projector that keeps turning off is a piece of equipment you can't rely on. The answer names the category and the problem, not the details.",
    trap: "'His handouts are missing' copies 'handouts', but they're his backup plan. 'He has to turn off the lights for his presentation' reuses 'turn off' and 'presentation', but it's the projector that turns off, by itself.",
  },
];
