-- ════════════════════════════════════════════════════════════════════════
-- FICHIER GÉNÉRÉ par scripts/gen-economy-sql.mjs depuis src/data/chestCatalog.js — NE PAS ÉDITER.
-- Catalogues de l'économie côté serveur (lot 1 du chantier « économie côté serveur », 2026-09-24).
-- Tables SANS accès client (verrou du 2026-09-15) : seules les RPC SECURITY DEFINER les lisent.
-- ════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.shop_catalog (
  item_id text PRIMARY KEY, category text NOT NULL, ref_id text NOT NULL,
  price integer NOT NULL CHECK (price > 0), rarity text, one_shot boolean NOT NULL);
CREATE TABLE IF NOT EXISTS public.reward_catalog (
  reward_type text NOT NULL, reward_id text NOT NULL, rarity text NOT NULL, exclusive boolean NOT NULL,
  PRIMARY KEY (reward_type, reward_id));
CREATE TABLE IF NOT EXISTS public.token_catalog (
  token_type text PRIMARY KEY, cap integer NOT NULL CHECK (cap > 0), premium boolean NOT NULL, boost boolean NOT NULL);
CREATE TABLE IF NOT EXISTS public.chest_drop_tables (chest_type text PRIMARY KEY, slots jsonb NOT NULL);
CREATE TABLE IF NOT EXISTS public.rarity_catalog (id text PRIMARY KEY, tier integer NOT NULL);
CREATE TABLE IF NOT EXISTS public.chest_triggers (
  trigger text PRIMARY KEY, chest_type text NOT NULL, cooldown_days integer);

ALTER TABLE public.shop_catalog ENABLE ROW LEVEL SECURITY;
REVOKE SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.shop_catalog FROM anon, authenticated, public;
ALTER TABLE public.reward_catalog ENABLE ROW LEVEL SECURITY;
REVOKE SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.reward_catalog FROM anon, authenticated, public;
ALTER TABLE public.token_catalog ENABLE ROW LEVEL SECURITY;
REVOKE SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.token_catalog FROM anon, authenticated, public;
ALTER TABLE public.chest_drop_tables ENABLE ROW LEVEL SECURITY;
REVOKE SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.chest_drop_tables FROM anon, authenticated, public;
ALTER TABLE public.rarity_catalog ENABLE ROW LEVEL SECURITY;
REVOKE SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.rarity_catalog FROM anon, authenticated, public;
ALTER TABLE public.chest_triggers ENABLE ROW LEVEL SECURITY;
REVOKE SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON public.chest_triggers FROM anon, authenticated, public;

BEGIN;
DELETE FROM public.shop_catalog; DELETE FROM public.reward_catalog; DELETE FROM public.token_catalog;
DELETE FROM public.chest_drop_tables; DELETE FROM public.rarity_catalog; DELETE FROM public.chest_triggers;
INSERT INTO public.chest_triggers (trigger, chest_type, cooldown_days) VALUES
  ('xp_1k', 'novice', NULL),
  ('xp_3k', 'novice', NULL),
  ('xp_5k', 'novice', NULL),
  ('xp_10k', 'guerrier', NULL),
  ('xp_20k', 'guerrier', NULL),
  ('xp_30k', 'champion', NULL),
  ('xp_50k', 'champion', NULL),
  ('streak_7', 'novice', NULL),
  ('streak_30', 'guerrier', NULL),
  ('streak_100', 'champion', NULL),
  ('league_up_bronze', 'guerrier', NULL),
  ('league_up_silver', 'guerrier', NULL),
  ('league_up_gold', 'guerrier', NULL),
  ('league_up_platinum', 'guerrier', NULL),
  ('league_up_diamond', 'guerrier', NULL),
  ('league_up_champion', 'guerrier', NULL),
  ('league_up_legend', 'guerrier', NULL),
  ('boss_test', 'legendaire', NULL),
  ('mock_1', 'champion', NULL),
  ('mock_2', 'champion', NULL),
  ('mock_3', 'champion', NULL),
  ('ach_legendary_boss_complete', 'legendaire', NULL),
  ('ach_legendary_boss_800', 'legendaire', NULL),
  ('ach_legendary_legend_league', 'legendaire', NULL),
  ('ach_legendary_toeic_master', 'legendaire', NULL),
  ('ach_legendary_gauntlet_champion', 'legendaire', NULL),
  ('ach_legendary_gauntlet_grinder', 'legendaire', NULL),
  ('ach_legendary_gauntlet_scholar', 'legendaire', NULL),
  ('ach_epic_crypt_perfect', 'guerrier', NULL),
  ('ach_epic_chrono_perfect', 'guerrier', NULL),
  ('ach_epic_forge_perfect', 'guerrier', NULL),
  ('ach_epic_weaver_perfect', 'guerrier', NULL),
  ('ach_epic_irregular_master', 'guerrier', NULL),
  ('ach_epic_tense_sage', 'guerrier', NULL),
  ('ach_epic_passive_alchemist', 'guerrier', NULL),
  ('ach_epic_relative_weaver', 'guerrier', NULL),
  ('ach_novice_crypt_first', 'novice', NULL),
  ('ach_novice_chrono_first', 'novice', NULL),
  ('ach_novice_forge_first', 'novice', NULL),
  ('ach_novice_weaver_first', 'novice', NULL),
  ('ach_novice_gauntlet_explorer', 'novice', NULL),
  ('mastery_ablitz', 'champion', NULL),
  ('mastery_ablitz_2', 'champion', NULL),
  ('mastery_ablitz_3', 'legendaire', NULL),
  ('mastery_ablitz_4', 'champion', NULL),
  ('mastery_ablitz_5', 'champion', NULL),
  ('mastery_ablitz_6', 'champion', NULL),
  ('mastery_ablitz_7', 'champion', NULL),
  ('mastery_ablitz_8', 'champion', NULL),
  ('mastery_ablitz_9', 'champion', NULL),
  ('mastery_ablitz_10', 'champion', NULL),
  ('mastery_ablitz_11', 'champion', NULL),
  ('mastery_ablitz_12', 'champion', NULL),
  ('mastery_ablitz_13', 'champion', NULL),
  ('mastery_ablitz_14', 'champion', NULL),
  ('mastery_ablitz_15', 'champion', NULL),
  ('mastery_ablitz_16', 'champion', NULL),
  ('mastery_ablitz_17', 'champion', NULL),
  ('mastery_ablitz_18', 'champion', NULL),
  ('mastery_ablitz_19', 'champion', NULL),
  ('mastery_ablitz_20', 'champion', NULL),
  ('mastery_ablitz_21', 'champion', NULL),
  ('mastery_ablitz_22', 'champion', NULL),
  ('mastery_ablitz_23', 'champion', NULL),
  ('mastery_ablitz_24', 'champion', NULL),
  ('mastery_ablitz_25', 'champion', NULL),
  ('mastery_ablitz_26', 'champion', NULL),
  ('mastery_ablitz_27', 'champion', NULL),
  ('mastery_ablitz_28', 'champion', NULL),
  ('mastery_ablitz_29', 'champion', NULL),
  ('mastery_ablitz_30', 'champion', NULL),
  ('mastery_bforge', 'champion', NULL),
  ('mastery_bforge_2', 'champion', NULL),
  ('mastery_bforge_3', 'legendaire', NULL),
  ('mastery_bforge_4', 'champion', NULL),
  ('mastery_bforge_5', 'champion', NULL),
  ('mastery_bforge_6', 'champion', NULL),
  ('mastery_bforge_7', 'champion', NULL),
  ('mastery_bforge_8', 'champion', NULL),
  ('mastery_bforge_9', 'champion', NULL),
  ('mastery_bforge_10', 'champion', NULL),
  ('mastery_bforge_11', 'champion', NULL),
  ('mastery_bforge_12', 'champion', NULL),
  ('mastery_bforge_13', 'champion', NULL),
  ('mastery_bforge_14', 'champion', NULL),
  ('mastery_bforge_15', 'champion', NULL),
  ('mastery_bforge_16', 'champion', NULL),
  ('mastery_bforge_17', 'champion', NULL),
  ('mastery_bforge_18', 'champion', NULL),
  ('mastery_bforge_19', 'champion', NULL),
  ('mastery_bforge_20', 'champion', NULL),
  ('mastery_bforge_21', 'champion', NULL),
  ('mastery_bforge_22', 'champion', NULL),
  ('mastery_bforge_23', 'champion', NULL),
  ('mastery_bforge_24', 'champion', NULL),
  ('mastery_bforge_25', 'champion', NULL),
  ('mastery_bforge_26', 'champion', NULL),
  ('mastery_bforge_27', 'champion', NULL),
  ('mastery_bforge_28', 'champion', NULL),
  ('mastery_bforge_29', 'champion', NULL),
  ('mastery_bforge_30', 'champion', NULL),
  ('mastery_cdom', 'champion', NULL),
  ('mastery_cdom_2', 'champion', NULL),
  ('mastery_cdom_3', 'legendaire', NULL),
  ('mastery_cdom_4', 'champion', NULL),
  ('mastery_cdom_5', 'champion', NULL),
  ('mastery_cdom_6', 'champion', NULL),
  ('mastery_cdom_7', 'champion', NULL),
  ('mastery_cdom_8', 'champion', NULL),
  ('mastery_cdom_9', 'champion', NULL),
  ('mastery_cdom_10', 'champion', NULL),
  ('mastery_cdom_11', 'champion', NULL),
  ('mastery_cdom_12', 'champion', NULL),
  ('mastery_cdom_13', 'champion', NULL),
  ('mastery_cdom_14', 'champion', NULL),
  ('mastery_cdom_15', 'champion', NULL),
  ('mastery_cdom_16', 'champion', NULL),
  ('mastery_cdom_17', 'champion', NULL),
  ('mastery_cdom_18', 'champion', NULL),
  ('mastery_cdom_19', 'champion', NULL),
  ('mastery_cdom_20', 'champion', NULL),
  ('mastery_cdom_21', 'champion', NULL),
  ('mastery_cdom_22', 'champion', NULL),
  ('mastery_cdom_23', 'champion', NULL),
  ('mastery_cdom_24', 'champion', NULL),
  ('mastery_cdom_25', 'champion', NULL),
  ('mastery_cdom_26', 'champion', NULL),
  ('mastery_cdom_27', 'champion', NULL),
  ('mastery_cdom_28', 'champion', NULL),
  ('mastery_cdom_29', 'champion', NULL),
  ('mastery_cdom_30', 'champion', NULL),
  ('mastery_clue', 'champion', NULL),
  ('mastery_clue_2', 'champion', NULL),
  ('mastery_clue_3', 'legendaire', NULL),
  ('mastery_clue_4', 'champion', NULL),
  ('mastery_clue_5', 'champion', NULL),
  ('mastery_clue_6', 'champion', NULL),
  ('mastery_clue_7', 'champion', NULL),
  ('mastery_clue_8', 'champion', NULL),
  ('mastery_clue_9', 'champion', NULL),
  ('mastery_clue_10', 'champion', NULL),
  ('mastery_clue_11', 'champion', NULL),
  ('mastery_clue_12', 'champion', NULL),
  ('mastery_clue_13', 'champion', NULL),
  ('mastery_clue_14', 'champion', NULL),
  ('mastery_clue_15', 'champion', NULL),
  ('mastery_clue_16', 'champion', NULL),
  ('mastery_clue_17', 'champion', NULL),
  ('mastery_clue_18', 'champion', NULL),
  ('mastery_clue_19', 'champion', NULL),
  ('mastery_clue_20', 'champion', NULL),
  ('mastery_clue_21', 'champion', NULL),
  ('mastery_clue_22', 'champion', NULL),
  ('mastery_clue_23', 'champion', NULL),
  ('mastery_clue_24', 'champion', NULL),
  ('mastery_clue_25', 'champion', NULL),
  ('mastery_clue_26', 'champion', NULL),
  ('mastery_clue_27', 'champion', NULL),
  ('mastery_clue_28', 'champion', NULL),
  ('mastery_clue_29', 'champion', NULL),
  ('mastery_clue_30', 'champion', NULL),
  ('mastery_connsort', 'champion', NULL),
  ('mastery_connsort_2', 'champion', NULL),
  ('mastery_connsort_3', 'legendaire', NULL),
  ('mastery_connsort_4', 'champion', NULL),
  ('mastery_connsort_5', 'champion', NULL),
  ('mastery_connsort_6', 'champion', NULL),
  ('mastery_connsort_7', 'champion', NULL),
  ('mastery_connsort_8', 'champion', NULL),
  ('mastery_connsort_9', 'champion', NULL),
  ('mastery_connsort_10', 'champion', NULL),
  ('mastery_connsort_11', 'champion', NULL),
  ('mastery_connsort_12', 'champion', NULL),
  ('mastery_connsort_13', 'champion', NULL),
  ('mastery_connsort_14', 'champion', NULL),
  ('mastery_connsort_15', 'champion', NULL),
  ('mastery_connsort_16', 'champion', NULL),
  ('mastery_connsort_17', 'champion', NULL),
  ('mastery_connsort_18', 'champion', NULL),
  ('mastery_connsort_19', 'champion', NULL),
  ('mastery_connsort_20', 'champion', NULL),
  ('mastery_connsort_21', 'champion', NULL),
  ('mastery_connsort_22', 'champion', NULL),
  ('mastery_connsort_23', 'champion', NULL),
  ('mastery_connsort_24', 'champion', NULL),
  ('mastery_connsort_25', 'champion', NULL),
  ('mastery_connsort_26', 'champion', NULL),
  ('mastery_connsort_27', 'champion', NULL),
  ('mastery_connsort_28', 'champion', NULL),
  ('mastery_connsort_29', 'champion', NULL),
  ('mastery_connsort_30', 'champion', NULL),
  ('mastery_drill', 'champion', NULL),
  ('mastery_drill_2', 'champion', NULL),
  ('mastery_drill_3', 'legendaire', NULL),
  ('mastery_drill_4', 'champion', NULL),
  ('mastery_drill_5', 'champion', NULL),
  ('mastery_drill_6', 'champion', NULL),
  ('mastery_drill_7', 'champion', NULL),
  ('mastery_drill_8', 'champion', NULL),
  ('mastery_drill_9', 'champion', NULL),
  ('mastery_drill_10', 'champion', NULL),
  ('mastery_drill_11', 'champion', NULL),
  ('mastery_drill_12', 'champion', NULL),
  ('mastery_drill_13', 'champion', NULL),
  ('mastery_drill_14', 'champion', NULL),
  ('mastery_drill_15', 'champion', NULL),
  ('mastery_drill_16', 'champion', NULL),
  ('mastery_drill_17', 'champion', NULL),
  ('mastery_drill_18', 'champion', NULL),
  ('mastery_drill_19', 'champion', NULL),
  ('mastery_drill_20', 'champion', NULL),
  ('mastery_drill_21', 'champion', NULL),
  ('mastery_drill_22', 'champion', NULL),
  ('mastery_drill_23', 'champion', NULL),
  ('mastery_drill_24', 'champion', NULL),
  ('mastery_drill_25', 'champion', NULL),
  ('mastery_drill_26', 'champion', NULL),
  ('mastery_drill_27', 'champion', NULL),
  ('mastery_drill_28', 'champion', NULL),
  ('mastery_drill_29', 'champion', NULL),
  ('mastery_drill_30', 'champion', NULL),
  ('mastery_endless', 'champion', NULL),
  ('mastery_endless_2', 'champion', NULL),
  ('mastery_endless_3', 'legendaire', NULL),
  ('mastery_endless_4', 'champion', NULL),
  ('mastery_endless_5', 'champion', NULL),
  ('mastery_endless_6', 'champion', NULL),
  ('mastery_endless_7', 'champion', NULL),
  ('mastery_endless_8', 'champion', NULL),
  ('mastery_endless_9', 'champion', NULL),
  ('mastery_endless_10', 'champion', NULL),
  ('mastery_endless_11', 'champion', NULL),
  ('mastery_endless_12', 'champion', NULL),
  ('mastery_endless_13', 'champion', NULL),
  ('mastery_endless_14', 'champion', NULL),
  ('mastery_endless_15', 'champion', NULL),
  ('mastery_endless_16', 'champion', NULL),
  ('mastery_endless_17', 'champion', NULL),
  ('mastery_endless_18', 'champion', NULL),
  ('mastery_endless_19', 'champion', NULL),
  ('mastery_endless_20', 'champion', NULL),
  ('mastery_endless_21', 'champion', NULL),
  ('mastery_endless_22', 'champion', NULL),
  ('mastery_endless_23', 'champion', NULL),
  ('mastery_endless_24', 'champion', NULL),
  ('mastery_endless_25', 'champion', NULL),
  ('mastery_endless_26', 'champion', NULL),
  ('mastery_endless_27', 'champion', NULL),
  ('mastery_endless_28', 'champion', NULL),
  ('mastery_endless_29', 'champion', NULL),
  ('mastery_endless_30', 'champion', NULL),
  ('mastery_falsefr', 'champion', NULL),
  ('mastery_falsefr_2', 'champion', NULL),
  ('mastery_falsefr_3', 'legendaire', NULL),
  ('mastery_falsefr_4', 'champion', NULL),
  ('mastery_falsefr_5', 'champion', NULL),
  ('mastery_falsefr_6', 'champion', NULL),
  ('mastery_falsefr_7', 'champion', NULL),
  ('mastery_falsefr_8', 'champion', NULL),
  ('mastery_falsefr_9', 'champion', NULL),
  ('mastery_falsefr_10', 'champion', NULL),
  ('mastery_falsefr_11', 'champion', NULL),
  ('mastery_falsefr_12', 'champion', NULL),
  ('mastery_falsefr_13', 'champion', NULL),
  ('mastery_falsefr_14', 'champion', NULL),
  ('mastery_falsefr_15', 'champion', NULL),
  ('mastery_falsefr_16', 'champion', NULL),
  ('mastery_falsefr_17', 'champion', NULL),
  ('mastery_falsefr_18', 'champion', NULL),
  ('mastery_falsefr_19', 'champion', NULL),
  ('mastery_falsefr_20', 'champion', NULL),
  ('mastery_falsefr_21', 'champion', NULL),
  ('mastery_falsefr_22', 'champion', NULL),
  ('mastery_falsefr_23', 'champion', NULL),
  ('mastery_falsefr_24', 'champion', NULL),
  ('mastery_falsefr_25', 'champion', NULL),
  ('mastery_falsefr_26', 'champion', NULL),
  ('mastery_falsefr_27', 'champion', NULL),
  ('mastery_falsefr_28', 'champion', NULL),
  ('mastery_falsefr_29', 'champion', NULL),
  ('mastery_falsefr_30', 'champion', NULL),
  ('mastery_gauntlet_irregular', 'champion', NULL),
  ('mastery_gauntlet_irregular_2', 'champion', NULL),
  ('mastery_gauntlet_irregular_3', 'legendaire', NULL),
  ('mastery_gauntlet_irregular_4', 'champion', NULL),
  ('mastery_gauntlet_irregular_5', 'champion', NULL),
  ('mastery_gauntlet_irregular_6', 'champion', NULL),
  ('mastery_gauntlet_irregular_7', 'champion', NULL),
  ('mastery_gauntlet_irregular_8', 'champion', NULL),
  ('mastery_gauntlet_irregular_9', 'champion', NULL),
  ('mastery_gauntlet_irregular_10', 'champion', NULL),
  ('mastery_gauntlet_irregular_11', 'champion', NULL),
  ('mastery_gauntlet_irregular_12', 'champion', NULL),
  ('mastery_gauntlet_irregular_13', 'champion', NULL),
  ('mastery_gauntlet_irregular_14', 'champion', NULL),
  ('mastery_gauntlet_irregular_15', 'champion', NULL),
  ('mastery_gauntlet_irregular_16', 'champion', NULL),
  ('mastery_gauntlet_irregular_17', 'champion', NULL),
  ('mastery_gauntlet_irregular_18', 'champion', NULL),
  ('mastery_gauntlet_irregular_19', 'champion', NULL),
  ('mastery_gauntlet_irregular_20', 'champion', NULL),
  ('mastery_gauntlet_irregular_21', 'champion', NULL),
  ('mastery_gauntlet_irregular_22', 'champion', NULL),
  ('mastery_gauntlet_irregular_23', 'champion', NULL),
  ('mastery_gauntlet_irregular_24', 'champion', NULL),
  ('mastery_gauntlet_irregular_25', 'champion', NULL),
  ('mastery_gauntlet_irregular_26', 'champion', NULL),
  ('mastery_gauntlet_irregular_27', 'champion', NULL),
  ('mastery_gauntlet_irregular_28', 'champion', NULL),
  ('mastery_gauntlet_irregular_29', 'champion', NULL),
  ('mastery_gauntlet_irregular_30', 'champion', NULL),
  ('mastery_gauntlet_passive', 'champion', NULL),
  ('mastery_gauntlet_passive_2', 'champion', NULL),
  ('mastery_gauntlet_passive_3', 'legendaire', NULL),
  ('mastery_gauntlet_passive_4', 'champion', NULL),
  ('mastery_gauntlet_passive_5', 'champion', NULL),
  ('mastery_gauntlet_passive_6', 'champion', NULL),
  ('mastery_gauntlet_passive_7', 'champion', NULL),
  ('mastery_gauntlet_passive_8', 'champion', NULL),
  ('mastery_gauntlet_passive_9', 'champion', NULL),
  ('mastery_gauntlet_passive_10', 'champion', NULL),
  ('mastery_gauntlet_passive_11', 'champion', NULL),
  ('mastery_gauntlet_passive_12', 'champion', NULL),
  ('mastery_gauntlet_passive_13', 'champion', NULL),
  ('mastery_gauntlet_passive_14', 'champion', NULL),
  ('mastery_gauntlet_passive_15', 'champion', NULL),
  ('mastery_gauntlet_passive_16', 'champion', NULL),
  ('mastery_gauntlet_passive_17', 'champion', NULL),
  ('mastery_gauntlet_passive_18', 'champion', NULL),
  ('mastery_gauntlet_passive_19', 'champion', NULL),
  ('mastery_gauntlet_passive_20', 'champion', NULL),
  ('mastery_gauntlet_passive_21', 'champion', NULL),
  ('mastery_gauntlet_passive_22', 'champion', NULL),
  ('mastery_gauntlet_passive_23', 'champion', NULL),
  ('mastery_gauntlet_passive_24', 'champion', NULL),
  ('mastery_gauntlet_passive_25', 'champion', NULL),
  ('mastery_gauntlet_passive_26', 'champion', NULL),
  ('mastery_gauntlet_passive_27', 'champion', NULL),
  ('mastery_gauntlet_passive_28', 'champion', NULL),
  ('mastery_gauntlet_passive_29', 'champion', NULL),
  ('mastery_gauntlet_passive_30', 'champion', NULL),
  ('mastery_gauntlet_relative', 'champion', NULL),
  ('mastery_gauntlet_relative_2', 'champion', NULL),
  ('mastery_gauntlet_relative_3', 'legendaire', NULL),
  ('mastery_gauntlet_relative_4', 'champion', NULL),
  ('mastery_gauntlet_relative_5', 'champion', NULL),
  ('mastery_gauntlet_relative_6', 'champion', NULL),
  ('mastery_gauntlet_relative_7', 'champion', NULL),
  ('mastery_gauntlet_relative_8', 'champion', NULL),
  ('mastery_gauntlet_relative_9', 'champion', NULL),
  ('mastery_gauntlet_relative_10', 'champion', NULL),
  ('mastery_gauntlet_relative_11', 'champion', NULL),
  ('mastery_gauntlet_relative_12', 'champion', NULL),
  ('mastery_gauntlet_relative_13', 'champion', NULL),
  ('mastery_gauntlet_relative_14', 'champion', NULL),
  ('mastery_gauntlet_relative_15', 'champion', NULL),
  ('mastery_gauntlet_relative_16', 'champion', NULL),
  ('mastery_gauntlet_relative_17', 'champion', NULL),
  ('mastery_gauntlet_relative_18', 'champion', NULL),
  ('mastery_gauntlet_relative_19', 'champion', NULL),
  ('mastery_gauntlet_relative_20', 'champion', NULL),
  ('mastery_gauntlet_relative_21', 'champion', NULL),
  ('mastery_gauntlet_relative_22', 'champion', NULL),
  ('mastery_gauntlet_relative_23', 'champion', NULL),
  ('mastery_gauntlet_relative_24', 'champion', NULL),
  ('mastery_gauntlet_relative_25', 'champion', NULL),
  ('mastery_gauntlet_relative_26', 'champion', NULL),
  ('mastery_gauntlet_relative_27', 'champion', NULL),
  ('mastery_gauntlet_relative_28', 'champion', NULL),
  ('mastery_gauntlet_relative_29', 'champion', NULL),
  ('mastery_gauntlet_relative_30', 'champion', NULL),
  ('mastery_gauntlet_tense', 'champion', NULL),
  ('mastery_gauntlet_tense_2', 'champion', NULL),
  ('mastery_gauntlet_tense_3', 'legendaire', NULL),
  ('mastery_gauntlet_tense_4', 'champion', NULL),
  ('mastery_gauntlet_tense_5', 'champion', NULL),
  ('mastery_gauntlet_tense_6', 'champion', NULL),
  ('mastery_gauntlet_tense_7', 'champion', NULL),
  ('mastery_gauntlet_tense_8', 'champion', NULL),
  ('mastery_gauntlet_tense_9', 'champion', NULL),
  ('mastery_gauntlet_tense_10', 'champion', NULL),
  ('mastery_gauntlet_tense_11', 'champion', NULL),
  ('mastery_gauntlet_tense_12', 'champion', NULL),
  ('mastery_gauntlet_tense_13', 'champion', NULL),
  ('mastery_gauntlet_tense_14', 'champion', NULL),
  ('mastery_gauntlet_tense_15', 'champion', NULL),
  ('mastery_gauntlet_tense_16', 'champion', NULL),
  ('mastery_gauntlet_tense_17', 'champion', NULL),
  ('mastery_gauntlet_tense_18', 'champion', NULL),
  ('mastery_gauntlet_tense_19', 'champion', NULL),
  ('mastery_gauntlet_tense_20', 'champion', NULL),
  ('mastery_gauntlet_tense_21', 'champion', NULL),
  ('mastery_gauntlet_tense_22', 'champion', NULL),
  ('mastery_gauntlet_tense_23', 'champion', NULL),
  ('mastery_gauntlet_tense_24', 'champion', NULL),
  ('mastery_gauntlet_tense_25', 'champion', NULL),
  ('mastery_gauntlet_tense_26', 'champion', NULL),
  ('mastery_gauntlet_tense_27', 'champion', NULL),
  ('mastery_gauntlet_tense_28', 'champion', NULL),
  ('mastery_gauntlet_tense_29', 'champion', NULL),
  ('mastery_gauntlet_tense_30', 'champion', NULL),
  ('mastery_gerinf', 'champion', NULL),
  ('mastery_gerinf_2', 'champion', NULL),
  ('mastery_gerinf_3', 'legendaire', NULL),
  ('mastery_gerinf_4', 'champion', NULL),
  ('mastery_gerinf_5', 'champion', NULL),
  ('mastery_gerinf_6', 'champion', NULL),
  ('mastery_gerinf_7', 'champion', NULL),
  ('mastery_gerinf_8', 'champion', NULL),
  ('mastery_gerinf_9', 'champion', NULL),
  ('mastery_gerinf_10', 'champion', NULL),
  ('mastery_gerinf_11', 'champion', NULL),
  ('mastery_gerinf_12', 'champion', NULL),
  ('mastery_gerinf_13', 'champion', NULL),
  ('mastery_gerinf_14', 'champion', NULL),
  ('mastery_gerinf_15', 'champion', NULL),
  ('mastery_gerinf_16', 'champion', NULL),
  ('mastery_gerinf_17', 'champion', NULL),
  ('mastery_gerinf_18', 'champion', NULL),
  ('mastery_gerinf_19', 'champion', NULL),
  ('mastery_gerinf_20', 'champion', NULL),
  ('mastery_gerinf_21', 'champion', NULL),
  ('mastery_gerinf_22', 'champion', NULL),
  ('mastery_gerinf_23', 'champion', NULL),
  ('mastery_gerinf_24', 'champion', NULL),
  ('mastery_gerinf_25', 'champion', NULL),
  ('mastery_gerinf_26', 'champion', NULL),
  ('mastery_gerinf_27', 'champion', NULL),
  ('mastery_gerinf_28', 'champion', NULL),
  ('mastery_gerinf_29', 'champion', NULL),
  ('mastery_gerinf_30', 'champion', NULL),
  ('mastery_lisP1', 'champion', NULL),
  ('mastery_lisP1_2', 'champion', NULL),
  ('mastery_lisP1_3', 'legendaire', NULL),
  ('mastery_lisP1_4', 'champion', NULL),
  ('mastery_lisP1_5', 'champion', NULL),
  ('mastery_lisP1_6', 'champion', NULL),
  ('mastery_lisP1_7', 'champion', NULL),
  ('mastery_lisP1_8', 'champion', NULL),
  ('mastery_lisP1_9', 'champion', NULL),
  ('mastery_lisP1_10', 'champion', NULL),
  ('mastery_lisP1_11', 'champion', NULL),
  ('mastery_lisP1_12', 'champion', NULL),
  ('mastery_lisP1_13', 'champion', NULL),
  ('mastery_lisP1_14', 'champion', NULL),
  ('mastery_lisP1_15', 'champion', NULL),
  ('mastery_lisP1_16', 'champion', NULL),
  ('mastery_lisP1_17', 'champion', NULL),
  ('mastery_lisP1_18', 'champion', NULL),
  ('mastery_lisP1_19', 'champion', NULL),
  ('mastery_lisP1_20', 'champion', NULL),
  ('mastery_lisP1_21', 'champion', NULL),
  ('mastery_lisP1_22', 'champion', NULL),
  ('mastery_lisP1_23', 'champion', NULL),
  ('mastery_lisP1_24', 'champion', NULL),
  ('mastery_lisP1_25', 'champion', NULL),
  ('mastery_lisP1_26', 'champion', NULL),
  ('mastery_lisP1_27', 'champion', NULL),
  ('mastery_lisP1_28', 'champion', NULL),
  ('mastery_lisP1_29', 'champion', NULL),
  ('mastery_lisP1_30', 'champion', NULL),
  ('mastery_lisP2', 'champion', NULL),
  ('mastery_lisP2_2', 'champion', NULL),
  ('mastery_lisP2_3', 'legendaire', NULL),
  ('mastery_lisP2_4', 'champion', NULL),
  ('mastery_lisP2_5', 'champion', NULL),
  ('mastery_lisP2_6', 'champion', NULL),
  ('mastery_lisP2_7', 'champion', NULL),
  ('mastery_lisP2_8', 'champion', NULL),
  ('mastery_lisP2_9', 'champion', NULL),
  ('mastery_lisP2_10', 'champion', NULL),
  ('mastery_lisP2_11', 'champion', NULL),
  ('mastery_lisP2_12', 'champion', NULL),
  ('mastery_lisP2_13', 'champion', NULL),
  ('mastery_lisP2_14', 'champion', NULL),
  ('mastery_lisP2_15', 'champion', NULL),
  ('mastery_lisP2_16', 'champion', NULL),
  ('mastery_lisP2_17', 'champion', NULL),
  ('mastery_lisP2_18', 'champion', NULL),
  ('mastery_lisP2_19', 'champion', NULL),
  ('mastery_lisP2_20', 'champion', NULL),
  ('mastery_lisP2_21', 'champion', NULL),
  ('mastery_lisP2_22', 'champion', NULL),
  ('mastery_lisP2_23', 'champion', NULL),
  ('mastery_lisP2_24', 'champion', NULL),
  ('mastery_lisP2_25', 'champion', NULL),
  ('mastery_lisP2_26', 'champion', NULL),
  ('mastery_lisP2_27', 'champion', NULL),
  ('mastery_lisP2_28', 'champion', NULL),
  ('mastery_lisP2_29', 'champion', NULL),
  ('mastery_lisP2_30', 'champion', NULL),
  ('mastery_lisP3', 'champion', NULL),
  ('mastery_lisP3_2', 'champion', NULL),
  ('mastery_lisP3_3', 'legendaire', NULL),
  ('mastery_lisP3_4', 'champion', NULL),
  ('mastery_lisP3_5', 'champion', NULL),
  ('mastery_lisP3_6', 'champion', NULL),
  ('mastery_lisP3_7', 'champion', NULL),
  ('mastery_lisP3_8', 'champion', NULL),
  ('mastery_lisP3_9', 'champion', NULL),
  ('mastery_lisP3_10', 'champion', NULL),
  ('mastery_lisP3_11', 'champion', NULL),
  ('mastery_lisP3_12', 'champion', NULL),
  ('mastery_lisP3_13', 'champion', NULL),
  ('mastery_lisP3_14', 'champion', NULL),
  ('mastery_lisP3_15', 'champion', NULL),
  ('mastery_lisP3_16', 'champion', NULL),
  ('mastery_lisP3_17', 'champion', NULL),
  ('mastery_lisP3_18', 'champion', NULL),
  ('mastery_lisP3_19', 'champion', NULL),
  ('mastery_lisP3_20', 'champion', NULL),
  ('mastery_lisP3_21', 'champion', NULL),
  ('mastery_lisP3_22', 'champion', NULL),
  ('mastery_lisP3_23', 'champion', NULL),
  ('mastery_lisP3_24', 'champion', NULL),
  ('mastery_lisP3_25', 'champion', NULL),
  ('mastery_lisP3_26', 'champion', NULL),
  ('mastery_lisP3_27', 'champion', NULL),
  ('mastery_lisP3_28', 'champion', NULL),
  ('mastery_lisP3_29', 'champion', NULL),
  ('mastery_lisP3_30', 'champion', NULL),
  ('mastery_lisP4', 'champion', NULL),
  ('mastery_lisP4_2', 'champion', NULL),
  ('mastery_lisP4_3', 'legendaire', NULL),
  ('mastery_lisP4_4', 'champion', NULL),
  ('mastery_lisP4_5', 'champion', NULL),
  ('mastery_lisP4_6', 'champion', NULL),
  ('mastery_lisP4_7', 'champion', NULL),
  ('mastery_lisP4_8', 'champion', NULL),
  ('mastery_lisP4_9', 'champion', NULL),
  ('mastery_lisP4_10', 'champion', NULL),
  ('mastery_lisP4_11', 'champion', NULL),
  ('mastery_lisP4_12', 'champion', NULL),
  ('mastery_lisP4_13', 'champion', NULL),
  ('mastery_lisP4_14', 'champion', NULL),
  ('mastery_lisP4_15', 'champion', NULL),
  ('mastery_lisP4_16', 'champion', NULL),
  ('mastery_lisP4_17', 'champion', NULL),
  ('mastery_lisP4_18', 'champion', NULL),
  ('mastery_lisP4_19', 'champion', NULL),
  ('mastery_lisP4_20', 'champion', NULL),
  ('mastery_lisP4_21', 'champion', NULL),
  ('mastery_lisP4_22', 'champion', NULL),
  ('mastery_lisP4_23', 'champion', NULL),
  ('mastery_lisP4_24', 'champion', NULL),
  ('mastery_lisP4_25', 'champion', NULL),
  ('mastery_lisP4_26', 'champion', NULL),
  ('mastery_lisP4_27', 'champion', NULL),
  ('mastery_lisP4_28', 'champion', NULL),
  ('mastery_lisP4_29', 'champion', NULL),
  ('mastery_lisP4_30', 'champion', NULL),
  ('mastery_mimic', 'champion', NULL),
  ('mastery_mimic_2', 'champion', NULL),
  ('mastery_mimic_3', 'legendaire', NULL),
  ('mastery_mimic_4', 'champion', NULL),
  ('mastery_mimic_5', 'champion', NULL),
  ('mastery_mimic_6', 'champion', NULL),
  ('mastery_mimic_7', 'champion', NULL),
  ('mastery_mimic_8', 'champion', NULL),
  ('mastery_mimic_9', 'champion', NULL),
  ('mastery_mimic_10', 'champion', NULL),
  ('mastery_mimic_11', 'champion', NULL),
  ('mastery_mimic_12', 'champion', NULL),
  ('mastery_mimic_13', 'champion', NULL),
  ('mastery_mimic_14', 'champion', NULL),
  ('mastery_mimic_15', 'champion', NULL),
  ('mastery_mimic_16', 'champion', NULL),
  ('mastery_mimic_17', 'champion', NULL),
  ('mastery_mimic_18', 'champion', NULL),
  ('mastery_mimic_19', 'champion', NULL),
  ('mastery_mimic_20', 'champion', NULL),
  ('mastery_mimic_21', 'champion', NULL),
  ('mastery_mimic_22', 'champion', NULL),
  ('mastery_mimic_23', 'champion', NULL),
  ('mastery_mimic_24', 'champion', NULL),
  ('mastery_mimic_25', 'champion', NULL),
  ('mastery_mimic_26', 'champion', NULL),
  ('mastery_mimic_27', 'champion', NULL),
  ('mastery_mimic_28', 'champion', NULL),
  ('mastery_mimic_29', 'champion', NULL),
  ('mastery_mimic_30', 'champion', NULL),
  ('mastery_mimic_listen', 'champion', NULL),
  ('mastery_mimic_listen_2', 'champion', NULL),
  ('mastery_mimic_listen_3', 'legendaire', NULL),
  ('mastery_mimic_listen_4', 'champion', NULL),
  ('mastery_mimic_listen_5', 'champion', NULL),
  ('mastery_mimic_listen_6', 'champion', NULL),
  ('mastery_mimic_listen_7', 'champion', NULL),
  ('mastery_mimic_listen_8', 'champion', NULL),
  ('mastery_mimic_listen_9', 'champion', NULL),
  ('mastery_mimic_listen_10', 'champion', NULL),
  ('mastery_mimic_listen_11', 'champion', NULL),
  ('mastery_mimic_listen_12', 'champion', NULL),
  ('mastery_mimic_listen_13', 'champion', NULL),
  ('mastery_mimic_listen_14', 'champion', NULL),
  ('mastery_mimic_listen_15', 'champion', NULL),
  ('mastery_mimic_listen_16', 'champion', NULL),
  ('mastery_mimic_listen_17', 'champion', NULL),
  ('mastery_mimic_listen_18', 'champion', NULL),
  ('mastery_mimic_listen_19', 'champion', NULL),
  ('mastery_mimic_listen_20', 'champion', NULL),
  ('mastery_mimic_listen_21', 'champion', NULL),
  ('mastery_mimic_listen_22', 'champion', NULL),
  ('mastery_mimic_listen_23', 'champion', NULL),
  ('mastery_mimic_listen_24', 'champion', NULL),
  ('mastery_mimic_listen_25', 'champion', NULL),
  ('mastery_mimic_listen_26', 'champion', NULL),
  ('mastery_mimic_listen_27', 'champion', NULL),
  ('mastery_mimic_listen_28', 'champion', NULL),
  ('mastery_mimic_listen_29', 'champion', NULL),
  ('mastery_mimic_listen_30', 'champion', NULL),
  ('mastery_modals_match', 'champion', NULL),
  ('mastery_modals_match_2', 'champion', NULL),
  ('mastery_modals_match_3', 'legendaire', NULL),
  ('mastery_modals_match_4', 'champion', NULL),
  ('mastery_modals_match_5', 'champion', NULL),
  ('mastery_modals_match_6', 'champion', NULL),
  ('mastery_modals_match_7', 'champion', NULL),
  ('mastery_modals_match_8', 'champion', NULL),
  ('mastery_modals_match_9', 'champion', NULL),
  ('mastery_modals_match_10', 'champion', NULL),
  ('mastery_modals_match_11', 'champion', NULL),
  ('mastery_modals_match_12', 'champion', NULL),
  ('mastery_modals_match_13', 'champion', NULL),
  ('mastery_modals_match_14', 'champion', NULL),
  ('mastery_modals_match_15', 'champion', NULL),
  ('mastery_modals_match_16', 'champion', NULL),
  ('mastery_modals_match_17', 'champion', NULL),
  ('mastery_modals_match_18', 'champion', NULL),
  ('mastery_modals_match_19', 'champion', NULL),
  ('mastery_modals_match_20', 'champion', NULL),
  ('mastery_modals_match_21', 'champion', NULL),
  ('mastery_modals_match_22', 'champion', NULL),
  ('mastery_modals_match_23', 'champion', NULL),
  ('mastery_modals_match_24', 'champion', NULL),
  ('mastery_modals_match_25', 'champion', NULL),
  ('mastery_modals_match_26', 'champion', NULL),
  ('mastery_modals_match_27', 'champion', NULL),
  ('mastery_modals_match_28', 'champion', NULL),
  ('mastery_modals_match_29', 'champion', NULL),
  ('mastery_modals_match_30', 'champion', NULL),
  ('mastery_modals_sort', 'champion', NULL),
  ('mastery_modals_sort_2', 'champion', NULL),
  ('mastery_modals_sort_3', 'legendaire', NULL),
  ('mastery_modals_sort_4', 'champion', NULL),
  ('mastery_modals_sort_5', 'champion', NULL),
  ('mastery_modals_sort_6', 'champion', NULL),
  ('mastery_modals_sort_7', 'champion', NULL),
  ('mastery_modals_sort_8', 'champion', NULL),
  ('mastery_modals_sort_9', 'champion', NULL),
  ('mastery_modals_sort_10', 'champion', NULL),
  ('mastery_modals_sort_11', 'champion', NULL),
  ('mastery_modals_sort_12', 'champion', NULL),
  ('mastery_modals_sort_13', 'champion', NULL),
  ('mastery_modals_sort_14', 'champion', NULL),
  ('mastery_modals_sort_15', 'champion', NULL),
  ('mastery_modals_sort_16', 'champion', NULL),
  ('mastery_modals_sort_17', 'champion', NULL),
  ('mastery_modals_sort_18', 'champion', NULL),
  ('mastery_modals_sort_19', 'champion', NULL),
  ('mastery_modals_sort_20', 'champion', NULL),
  ('mastery_modals_sort_21', 'champion', NULL),
  ('mastery_modals_sort_22', 'champion', NULL),
  ('mastery_modals_sort_23', 'champion', NULL),
  ('mastery_modals_sort_24', 'champion', NULL),
  ('mastery_modals_sort_25', 'champion', NULL),
  ('mastery_modals_sort_26', 'champion', NULL),
  ('mastery_modals_sort_27', 'champion', NULL),
  ('mastery_modals_sort_28', 'champion', NULL),
  ('mastery_modals_sort_29', 'champion', NULL),
  ('mastery_modals_sort_30', 'champion', NULL),
  ('mastery_p6', 'champion', NULL),
  ('mastery_p6_2', 'champion', NULL),
  ('mastery_p6_3', 'legendaire', NULL),
  ('mastery_p6_4', 'champion', NULL),
  ('mastery_p6_5', 'champion', NULL),
  ('mastery_p6_6', 'champion', NULL),
  ('mastery_p6_7', 'champion', NULL),
  ('mastery_p6_8', 'champion', NULL),
  ('mastery_p6_9', 'champion', NULL),
  ('mastery_p6_10', 'champion', NULL),
  ('mastery_p6_11', 'champion', NULL),
  ('mastery_p6_12', 'champion', NULL),
  ('mastery_p6_13', 'champion', NULL),
  ('mastery_p6_14', 'champion', NULL),
  ('mastery_p6_15', 'champion', NULL),
  ('mastery_p6_16', 'champion', NULL),
  ('mastery_p6_17', 'champion', NULL),
  ('mastery_p6_18', 'champion', NULL),
  ('mastery_p6_19', 'champion', NULL),
  ('mastery_p6_20', 'champion', NULL),
  ('mastery_p6_21', 'champion', NULL),
  ('mastery_p6_22', 'champion', NULL),
  ('mastery_p6_23', 'champion', NULL),
  ('mastery_p6_24', 'champion', NULL),
  ('mastery_p6_25', 'champion', NULL),
  ('mastery_p6_26', 'champion', NULL),
  ('mastery_p6_27', 'champion', NULL),
  ('mastery_p6_28', 'champion', NULL),
  ('mastery_p6_29', 'champion', NULL),
  ('mastery_p6_30', 'champion', NULL),
  ('mastery_p7', 'champion', NULL),
  ('mastery_p7_2', 'champion', NULL),
  ('mastery_p7_3', 'legendaire', NULL),
  ('mastery_p7_4', 'champion', NULL),
  ('mastery_p7_5', 'champion', NULL),
  ('mastery_p7_6', 'champion', NULL),
  ('mastery_p7_7', 'champion', NULL),
  ('mastery_p7_8', 'champion', NULL),
  ('mastery_p7_9', 'champion', NULL),
  ('mastery_p7_10', 'champion', NULL),
  ('mastery_p7_11', 'champion', NULL),
  ('mastery_p7_12', 'champion', NULL),
  ('mastery_p7_13', 'champion', NULL),
  ('mastery_p7_14', 'champion', NULL),
  ('mastery_p7_15', 'champion', NULL),
  ('mastery_p7_16', 'champion', NULL),
  ('mastery_p7_17', 'champion', NULL),
  ('mastery_p7_18', 'champion', NULL),
  ('mastery_p7_19', 'champion', NULL),
  ('mastery_p7_20', 'champion', NULL),
  ('mastery_p7_21', 'champion', NULL),
  ('mastery_p7_22', 'champion', NULL),
  ('mastery_p7_23', 'champion', NULL),
  ('mastery_p7_24', 'champion', NULL),
  ('mastery_p7_25', 'champion', NULL),
  ('mastery_p7_26', 'champion', NULL),
  ('mastery_p7_27', 'champion', NULL),
  ('mastery_p7_28', 'champion', NULL),
  ('mastery_p7_29', 'champion', NULL),
  ('mastery_p7_30', 'champion', NULL),
  ('mastery_phrasalpicker', 'champion', NULL),
  ('mastery_phrasalpicker_2', 'champion', NULL),
  ('mastery_phrasalpicker_3', 'legendaire', NULL),
  ('mastery_phrasalpicker_4', 'champion', NULL),
  ('mastery_phrasalpicker_5', 'champion', NULL),
  ('mastery_phrasalpicker_6', 'champion', NULL),
  ('mastery_phrasalpicker_7', 'champion', NULL),
  ('mastery_phrasalpicker_8', 'champion', NULL),
  ('mastery_phrasalpicker_9', 'champion', NULL),
  ('mastery_phrasalpicker_10', 'champion', NULL),
  ('mastery_phrasalpicker_11', 'champion', NULL),
  ('mastery_phrasalpicker_12', 'champion', NULL),
  ('mastery_phrasalpicker_13', 'champion', NULL),
  ('mastery_phrasalpicker_14', 'champion', NULL),
  ('mastery_phrasalpicker_15', 'champion', NULL),
  ('mastery_phrasalpicker_16', 'champion', NULL),
  ('mastery_phrasalpicker_17', 'champion', NULL),
  ('mastery_phrasalpicker_18', 'champion', NULL),
  ('mastery_phrasalpicker_19', 'champion', NULL),
  ('mastery_phrasalpicker_20', 'champion', NULL),
  ('mastery_phrasalpicker_21', 'champion', NULL),
  ('mastery_phrasalpicker_22', 'champion', NULL),
  ('mastery_phrasalpicker_23', 'champion', NULL),
  ('mastery_phrasalpicker_24', 'champion', NULL),
  ('mastery_phrasalpicker_25', 'champion', NULL),
  ('mastery_phrasalpicker_26', 'champion', NULL),
  ('mastery_phrasalpicker_27', 'champion', NULL),
  ('mastery_phrasalpicker_28', 'champion', NULL),
  ('mastery_phrasalpicker_29', 'champion', NULL),
  ('mastery_phrasalpicker_30', 'champion', NULL),
  ('mastery_prepdrill', 'champion', NULL),
  ('mastery_prepdrill_2', 'champion', NULL),
  ('mastery_prepdrill_3', 'legendaire', NULL),
  ('mastery_prepdrill_4', 'champion', NULL),
  ('mastery_prepdrill_5', 'champion', NULL),
  ('mastery_prepdrill_6', 'champion', NULL),
  ('mastery_prepdrill_7', 'champion', NULL),
  ('mastery_prepdrill_8', 'champion', NULL),
  ('mastery_prepdrill_9', 'champion', NULL),
  ('mastery_prepdrill_10', 'champion', NULL),
  ('mastery_prepdrill_11', 'champion', NULL),
  ('mastery_prepdrill_12', 'champion', NULL),
  ('mastery_prepdrill_13', 'champion', NULL),
  ('mastery_prepdrill_14', 'champion', NULL),
  ('mastery_prepdrill_15', 'champion', NULL),
  ('mastery_prepdrill_16', 'champion', NULL),
  ('mastery_prepdrill_17', 'champion', NULL),
  ('mastery_prepdrill_18', 'champion', NULL),
  ('mastery_prepdrill_19', 'champion', NULL),
  ('mastery_prepdrill_20', 'champion', NULL),
  ('mastery_prepdrill_21', 'champion', NULL),
  ('mastery_prepdrill_22', 'champion', NULL),
  ('mastery_prepdrill_23', 'champion', NULL),
  ('mastery_prepdrill_24', 'champion', NULL),
  ('mastery_prepdrill_25', 'champion', NULL),
  ('mastery_prepdrill_26', 'champion', NULL),
  ('mastery_prepdrill_27', 'champion', NULL),
  ('mastery_prepdrill_28', 'champion', NULL),
  ('mastery_prepdrill_29', 'champion', NULL),
  ('mastery_prepdrill_30', 'champion', NULL),
  ('mastery_pvdojo', 'champion', NULL),
  ('mastery_pvdojo_2', 'champion', NULL),
  ('mastery_pvdojo_3', 'legendaire', NULL),
  ('mastery_pvdojo_4', 'champion', NULL),
  ('mastery_pvdojo_5', 'champion', NULL),
  ('mastery_pvdojo_6', 'champion', NULL),
  ('mastery_pvdojo_7', 'champion', NULL),
  ('mastery_pvdojo_8', 'champion', NULL),
  ('mastery_pvdojo_9', 'champion', NULL),
  ('mastery_pvdojo_10', 'champion', NULL),
  ('mastery_pvdojo_11', 'champion', NULL),
  ('mastery_pvdojo_12', 'champion', NULL),
  ('mastery_pvdojo_13', 'champion', NULL),
  ('mastery_pvdojo_14', 'champion', NULL),
  ('mastery_pvdojo_15', 'champion', NULL),
  ('mastery_pvdojo_16', 'champion', NULL),
  ('mastery_pvdojo_17', 'champion', NULL),
  ('mastery_pvdojo_18', 'champion', NULL),
  ('mastery_pvdojo_19', 'champion', NULL),
  ('mastery_pvdojo_20', 'champion', NULL),
  ('mastery_pvdojo_21', 'champion', NULL),
  ('mastery_pvdojo_22', 'champion', NULL),
  ('mastery_pvdojo_23', 'champion', NULL),
  ('mastery_pvdojo_24', 'champion', NULL),
  ('mastery_pvdojo_25', 'champion', NULL),
  ('mastery_pvdojo_26', 'champion', NULL),
  ('mastery_pvdojo_27', 'champion', NULL),
  ('mastery_pvdojo_28', 'champion', NULL),
  ('mastery_pvdojo_29', 'champion', NULL),
  ('mastery_pvdojo_30', 'champion', NULL),
  ('mastery_sbuild', 'champion', NULL),
  ('mastery_sbuild_2', 'champion', NULL),
  ('mastery_sbuild_3', 'legendaire', NULL),
  ('mastery_sbuild_4', 'champion', NULL),
  ('mastery_sbuild_5', 'champion', NULL),
  ('mastery_sbuild_6', 'champion', NULL),
  ('mastery_sbuild_7', 'champion', NULL),
  ('mastery_sbuild_8', 'champion', NULL),
  ('mastery_sbuild_9', 'champion', NULL),
  ('mastery_sbuild_10', 'champion', NULL),
  ('mastery_sbuild_11', 'champion', NULL),
  ('mastery_sbuild_12', 'champion', NULL),
  ('mastery_sbuild_13', 'champion', NULL),
  ('mastery_sbuild_14', 'champion', NULL),
  ('mastery_sbuild_15', 'champion', NULL),
  ('mastery_sbuild_16', 'champion', NULL),
  ('mastery_sbuild_17', 'champion', NULL),
  ('mastery_sbuild_18', 'champion', NULL),
  ('mastery_sbuild_19', 'champion', NULL),
  ('mastery_sbuild_20', 'champion', NULL),
  ('mastery_sbuild_21', 'champion', NULL),
  ('mastery_sbuild_22', 'champion', NULL),
  ('mastery_sbuild_23', 'champion', NULL),
  ('mastery_sbuild_24', 'champion', NULL),
  ('mastery_sbuild_25', 'champion', NULL),
  ('mastery_sbuild_26', 'champion', NULL),
  ('mastery_sbuild_27', 'champion', NULL),
  ('mastery_sbuild_28', 'champion', NULL),
  ('mastery_sbuild_29', 'champion', NULL),
  ('mastery_sbuild_30', 'champion', NULL),
  ('mastery_stratquiz', 'champion', NULL),
  ('mastery_stratquiz_2', 'champion', NULL),
  ('mastery_stratquiz_3', 'legendaire', NULL),
  ('mastery_stratquiz_4', 'champion', NULL),
  ('mastery_stratquiz_5', 'champion', NULL),
  ('mastery_stratquiz_6', 'champion', NULL),
  ('mastery_stratquiz_7', 'champion', NULL),
  ('mastery_stratquiz_8', 'champion', NULL),
  ('mastery_stratquiz_9', 'champion', NULL),
  ('mastery_stratquiz_10', 'champion', NULL),
  ('mastery_stratquiz_11', 'champion', NULL),
  ('mastery_stratquiz_12', 'champion', NULL),
  ('mastery_stratquiz_13', 'champion', NULL),
  ('mastery_stratquiz_14', 'champion', NULL),
  ('mastery_stratquiz_15', 'champion', NULL),
  ('mastery_stratquiz_16', 'champion', NULL),
  ('mastery_stratquiz_17', 'champion', NULL),
  ('mastery_stratquiz_18', 'champion', NULL),
  ('mastery_stratquiz_19', 'champion', NULL),
  ('mastery_stratquiz_20', 'champion', NULL),
  ('mastery_stratquiz_21', 'champion', NULL),
  ('mastery_stratquiz_22', 'champion', NULL),
  ('mastery_stratquiz_23', 'champion', NULL),
  ('mastery_stratquiz_24', 'champion', NULL),
  ('mastery_stratquiz_25', 'champion', NULL),
  ('mastery_stratquiz_26', 'champion', NULL),
  ('mastery_stratquiz_27', 'champion', NULL),
  ('mastery_stratquiz_28', 'champion', NULL),
  ('mastery_stratquiz_29', 'champion', NULL),
  ('mastery_stratquiz_30', 'champion', NULL),
  ('mastery_tavern', 'champion', NULL),
  ('mastery_tavern_2', 'champion', NULL),
  ('mastery_tavern_3', 'legendaire', NULL),
  ('mastery_tavern_4', 'champion', NULL),
  ('mastery_tavern_5', 'champion', NULL),
  ('mastery_tavern_6', 'champion', NULL),
  ('mastery_tavern_7', 'champion', NULL),
  ('mastery_tavern_8', 'champion', NULL),
  ('mastery_tavern_9', 'champion', NULL),
  ('mastery_tavern_10', 'champion', NULL),
  ('mastery_tavern_11', 'champion', NULL),
  ('mastery_tavern_12', 'champion', NULL),
  ('mastery_tavern_13', 'champion', NULL),
  ('mastery_tavern_14', 'champion', NULL),
  ('mastery_tavern_15', 'champion', NULL),
  ('mastery_tavern_16', 'champion', NULL),
  ('mastery_tavern_17', 'champion', NULL),
  ('mastery_tavern_18', 'champion', NULL),
  ('mastery_tavern_19', 'champion', NULL),
  ('mastery_tavern_20', 'champion', NULL),
  ('mastery_tavern_21', 'champion', NULL),
  ('mastery_tavern_22', 'champion', NULL),
  ('mastery_tavern_23', 'champion', NULL),
  ('mastery_tavern_24', 'champion', NULL),
  ('mastery_tavern_25', 'champion', NULL),
  ('mastery_tavern_26', 'champion', NULL),
  ('mastery_tavern_27', 'champion', NULL),
  ('mastery_tavern_28', 'champion', NULL),
  ('mastery_tavern_29', 'champion', NULL),
  ('mastery_tavern_30', 'champion', NULL),
  ('mastery_timesim', 'champion', NULL),
  ('mastery_timesim_2', 'champion', NULL),
  ('mastery_timesim_3', 'legendaire', NULL),
  ('mastery_timesim_4', 'champion', NULL),
  ('mastery_timesim_5', 'champion', NULL),
  ('mastery_timesim_6', 'champion', NULL),
  ('mastery_timesim_7', 'champion', NULL),
  ('mastery_timesim_8', 'champion', NULL),
  ('mastery_timesim_9', 'champion', NULL),
  ('mastery_timesim_10', 'champion', NULL),
  ('mastery_timesim_11', 'champion', NULL),
  ('mastery_timesim_12', 'champion', NULL),
  ('mastery_timesim_13', 'champion', NULL),
  ('mastery_timesim_14', 'champion', NULL),
  ('mastery_timesim_15', 'champion', NULL),
  ('mastery_timesim_16', 'champion', NULL),
  ('mastery_timesim_17', 'champion', NULL),
  ('mastery_timesim_18', 'champion', NULL),
  ('mastery_timesim_19', 'champion', NULL),
  ('mastery_timesim_20', 'champion', NULL),
  ('mastery_timesim_21', 'champion', NULL),
  ('mastery_timesim_22', 'champion', NULL),
  ('mastery_timesim_23', 'champion', NULL),
  ('mastery_timesim_24', 'champion', NULL),
  ('mastery_timesim_25', 'champion', NULL),
  ('mastery_timesim_26', 'champion', NULL),
  ('mastery_timesim_27', 'champion', NULL),
  ('mastery_timesim_28', 'champion', NULL),
  ('mastery_timesim_29', 'champion', NULL),
  ('mastery_timesim_30', 'champion', NULL),
  ('mastery_traps', 'champion', NULL),
  ('mastery_traps_2', 'champion', NULL),
  ('mastery_traps_3', 'legendaire', NULL),
  ('mastery_traps_4', 'champion', NULL),
  ('mastery_traps_5', 'champion', NULL),
  ('mastery_traps_6', 'champion', NULL),
  ('mastery_traps_7', 'champion', NULL),
  ('mastery_traps_8', 'champion', NULL),
  ('mastery_traps_9', 'champion', NULL),
  ('mastery_traps_10', 'champion', NULL),
  ('mastery_traps_11', 'champion', NULL),
  ('mastery_traps_12', 'champion', NULL),
  ('mastery_traps_13', 'champion', NULL),
  ('mastery_traps_14', 'champion', NULL),
  ('mastery_traps_15', 'champion', NULL),
  ('mastery_traps_16', 'champion', NULL),
  ('mastery_traps_17', 'champion', NULL),
  ('mastery_traps_18', 'champion', NULL),
  ('mastery_traps_19', 'champion', NULL),
  ('mastery_traps_20', 'champion', NULL),
  ('mastery_traps_21', 'champion', NULL),
  ('mastery_traps_22', 'champion', NULL),
  ('mastery_traps_23', 'champion', NULL),
  ('mastery_traps_24', 'champion', NULL),
  ('mastery_traps_25', 'champion', NULL),
  ('mastery_traps_26', 'champion', NULL),
  ('mastery_traps_27', 'champion', NULL),
  ('mastery_traps_28', 'champion', NULL),
  ('mastery_traps_29', 'champion', NULL),
  ('mastery_traps_30', 'champion', NULL),
  ('mastery_wordfam', 'champion', NULL),
  ('mastery_wordfam_2', 'champion', NULL),
  ('mastery_wordfam_3', 'legendaire', NULL),
  ('mastery_wordfam_4', 'champion', NULL),
  ('mastery_wordfam_5', 'champion', NULL),
  ('mastery_wordfam_6', 'champion', NULL),
  ('mastery_wordfam_7', 'champion', NULL),
  ('mastery_wordfam_8', 'champion', NULL),
  ('mastery_wordfam_9', 'champion', NULL),
  ('mastery_wordfam_10', 'champion', NULL),
  ('mastery_wordfam_11', 'champion', NULL),
  ('mastery_wordfam_12', 'champion', NULL),
  ('mastery_wordfam_13', 'champion', NULL),
  ('mastery_wordfam_14', 'champion', NULL),
  ('mastery_wordfam_15', 'champion', NULL),
  ('mastery_wordfam_16', 'champion', NULL),
  ('mastery_wordfam_17', 'champion', NULL),
  ('mastery_wordfam_18', 'champion', NULL),
  ('mastery_wordfam_19', 'champion', NULL),
  ('mastery_wordfam_20', 'champion', NULL),
  ('mastery_wordfam_21', 'champion', NULL),
  ('mastery_wordfam_22', 'champion', NULL),
  ('mastery_wordfam_23', 'champion', NULL),
  ('mastery_wordfam_24', 'champion', NULL),
  ('mastery_wordfam_25', 'champion', NULL),
  ('mastery_wordfam_26', 'champion', NULL),
  ('mastery_wordfam_27', 'champion', NULL),
  ('mastery_wordfam_28', 'champion', NULL),
  ('mastery_wordfam_29', 'champion', NULL),
  ('mastery_wordfam_30', 'champion', NULL),
  ('duel_win', 'guerrier', 7),
  ('duel_win3', 'champion', 7),
  ('wfall_combo30', 'champion', 7),
  ('wfall_combo20', 'guerrier', 7),
  ('wfall_combo10', 'novice', 7),
  ('smatch_easy_good', 'novice', 7),
  ('sbuild_90', 'novice', 7),
  ('clue_perfect', 'guerrier', 7),
  ('ablitz_90', 'guerrier', 7),
  ('ablitz_70', 'novice', 7),
  ('gauntlet_irregular_perfect', 'guerrier', 7),
  ('gauntlet_tense_perfect', 'guerrier', 7),
  ('gauntlet_passive_perfect', 'guerrier', 7),
  ('gauntlet_relative_perfect', 'guerrier', 7),
  ('modals_match_perfect', 'guerrier', 7),
  ('modals_sort_perfect', 'guerrier', 7);
INSERT INTO public.chest_drop_tables (chest_type, slots) VALUES
  ('novice', '[{"kind":"daric","amount":30},{"kind":"xp","min":50,"max":150},{"kind":"token","pool":["diminishing_bypass","streak_shield","daily_reroll"],"count":1}]'::jsonb),
  ('guerrier', '[{"kind":"daric","amount":90},{"kind":"xp","min":200,"max":400},{"kind":"cosmetic","oneOf":["frame","title"]},{"kind":"token","pool":["diminishing_bypass","streak_shield","daily_reroll"],"count":2}]'::jsonb),
  ('champion', '[{"kind":"daric","amount":250},{"kind":"xp","min":500,"max":800},{"kind":"cosmetic","oneOf":["avatar","skin","frame","title"],"minRarity":"rare"},{"kind":"token","pool":["diminishing_bypass","daily_reroll","mock_reset","endless_resurrect"],"count":3}]'::jsonb),
  ('legendaire', '[{"kind":"daric","amount":700},{"kind":"xp","min":1000,"max":1500},{"kind":"cosmetic","oneOf":["avatar","skin"],"minRarity":"legend"},{"kind":"cosmetic","oneOf":["frame","title"],"minRarity":"epic"},{"kind":"token","pool":["diminishing_bypass","daily_reroll","mock_reset","boss_reset","endless_resurrect"],"count":3},{"kind":"cheat_sheet","chance":1},{"kind":"token","pool":["insight_token"],"count":1,"chance":0.3}]'::jsonb);
INSERT INTO public.rarity_catalog (id, tier) VALUES
  ('common', 0),
  ('uncommon', 1),
  ('rare', 2),
  ('epic', 3),
  ('legend', 4);
INSERT INTO public.shop_catalog (item_id, category, ref_id, price, rarity, one_shot) VALUES
  ('sk_frostbite', 'skin', 'frostbite', 1400, 'rare', true),
  ('sk_abyssal', 'skin', 'abyssal', 1400, 'rare', true),
  ('sk_emberheart', 'skin', 'emberheart', 2800, 'epic', true),
  ('sk_cosmic', 'skin', 'cosmic_void', 2800, 'epic', true),
  ('sk_molten', 'skin', 'molten_gold', 5800, 'legend', true),
  ('sk_heraldic', 'skin', 'heraldic', 5800, 'legend', true),
  ('sk_aldric', 'skin', 'aldric_chamber', 5800, 'legend', true),
  ('fr_arc', 'frame', 'arc_pulse', 400, 'rare', true),
  ('fr_halo', 'frame', 'gilded_halo', 750, 'epic', true),
  ('fr_orbit', 'frame', 'orbit', 750, 'epic', true),
  ('fr_tempest', 'frame', 'tempest', 750, 'epic', true),
  ('fr_inferno', 'frame', 'inferno_ring', 1400, 'legend', true),
  ('fr_prism', 'frame', 'prismatic', 1400, 'legend', true),
  ('ti_marchand', 'title', 'marchand_reliques', 200, 'rare', true),
  ('ti_arpenteur', 'title', 'arpenteur_comptoir', 250, 'rare', true),
  ('ti_tisseur', 'title', 'tisseur_darics', 350, 'epic', true),
  ('ti_oeil', 'title', 'oeil_aldric', 500, 'epic', true),
  ('tok_reroll', 'token', 'daily_reroll', 60, NULL, false),
  ('tok_bypass', 'token', 'diminishing_bypass', 90, NULL, false),
  ('tok_shield', 'token', 'streak_shield', 120, NULL, false),
  ('tok_mock', 'token', 'mock_reset', 150, NULL, false),
  ('tok_endless', 'token', 'endless_resurrect', 150, NULL, false),
  ('tok_boss', 'token', 'boss_reset', 220, NULL, false),
  ('tok_insight', 'token', 'insight_token', 300, NULL, false),
  ('boost_module', 'token', 'module_booster', 120, NULL, false),
  ('boost_mock', 'token', 'mock_multiplier', 220, NULL, false),
  ('boost_daily', 'token', 'daily_doubler', 400, NULL, false),
  ('cs_part5_conjunctions', 'cheat_sheet', 'part5_conjunctions', 700, 'epic', true),
  ('cs_part3_negation', 'cheat_sheet', 'part3_negation', 700, 'epic', true),
  ('cs_reading_skim_scan', 'cheat_sheet', 'reading_skim_scan', 450, 'rare', true),
  ('cs_part5_word_pairs', 'cheat_sheet', 'part5_word_pairs', 450, 'rare', true),
  ('cs_listening_reductions', 'cheat_sheet', 'listening_reductions', 450, 'rare', true),
  ('cs_part5_modals', 'cheat_sheet', 'part5_modals', 700, 'epic', true),
  ('cs_business_false_cognates', 'cheat_sheet', 'business_false_cognates', 700, 'epic', true),
  ('cs_part7_inference', 'cheat_sheet', 'part7_inference', 900, 'legend', true);
INSERT INTO public.reward_catalog (reward_type, reward_id, rarity, exclusive) VALUES
  ('avatar', 'paysan', 'common', false),
  ('avatar', 'ecuyer', 'common', false),
  ('avatar', 'apprenti', 'common', false),
  ('avatar', 'archer', 'common', false),
  ('avatar', 'forgeron', 'common', false),
  ('avatar', 'aubergiste', 'common', false),
  ('avatar', 'herboriste', 'common', false),
  ('avatar', 'barde', 'common', false),
  ('avatar', 'sentinelle', 'common', false),
  ('avatar', 'marchand', 'common', false),
  ('avatar', 'chevalier', 'uncommon', false),
  ('avatar', 'roublard', 'uncommon', false),
  ('avatar', 'sorcier', 'uncommon', false),
  ('avatar', 'rodeuse', 'uncommon', false),
  ('avatar', 'clerc', 'uncommon', false),
  ('avatar', 'alchimiste', 'uncommon', false),
  ('avatar', 'mercenaire', 'uncommon', false),
  ('avatar', 'erudit', 'uncommon', false),
  ('avatar', 'paladin', 'rare', false),
  ('avatar', 'archimage', 'rare', false),
  ('avatar', 'assassin', 'rare', false),
  ('avatar', 'druide', 'rare', false),
  ('avatar', 'mage_guerre', 'rare', false),
  ('avatar', 'seigneur', 'rare', false),
  ('avatar', 'valkyrie', 'rare', false),
  ('avatar', 'ch_dragon', 'epic', false),
  ('avatar', 'necro', 'epic', false),
  ('avatar', 'archere', 'epic', false),
  ('avatar', 'st_tempete', 'epic', false),
  ('avatar', 'inquisiteur', 'epic', false),
  ('avatar', 'pourfendeur', 'legend', false),
  ('avatar', 'champion', 'legend', false),
  ('avatar', 'warrior_queen_anais', 'legend', false),
  ('skin', 'argent', 'rare', false),
  ('skin', 'emeraude', 'rare', false),
  ('skin', 'saphir', 'rare', false),
  ('skin', 'rubis', 'epic', false),
  ('skin', 'amethyste', 'epic', false),
  ('skin', 'corail', 'epic', false),
  ('skin', 'jade', 'epic', false),
  ('skin', 'obsidienne', 'legend', false),
  ('skin', 'aurore', 'legend', false),
  ('skin', 'frostbite', 'rare', true),
  ('skin', 'abyssal', 'rare', true),
  ('skin', 'emberheart', 'epic', true),
  ('skin', 'cosmic_void', 'epic', true),
  ('skin', 'molten_gold', 'legend', true),
  ('skin', 'heraldic', 'legend', true),
  ('skin', 'aldric_chamber', 'legend', true),
  ('frame', 'gold_neon', 'rare', false),
  ('frame', 'emerald_glow', 'rare', false),
  ('frame', 'ice_crystal', 'rare', false),
  ('frame', 'fire_forged', 'epic', false),
  ('frame', 'ruby_aura', 'epic', false),
  ('frame', 'amethyst_veil', 'epic', false),
  ('frame', 'cosmic', 'legend', false),
  ('frame', 'dragonbone', 'legend', false),
  ('frame', 'arc_pulse', 'rare', true),
  ('frame', 'gilded_halo', 'epic', true),
  ('frame', 'orbit', 'epic', true),
  ('frame', 'tempest', 'epic', true),
  ('frame', 'inferno_ring', 'legend', true),
  ('frame', 'prismatic', 'legend', true),
  ('title', 'apprentice', 'rare', false),
  ('title', 'tavern_regular', 'rare', false),
  ('title', 'squire', 'rare', false),
  ('title', 'scribe', 'rare', false),
  ('title', 'wordsmith', 'epic', false),
  ('title', 'tense_sage', 'epic', false),
  ('title', 'drillmaster', 'epic', false),
  ('title', 'word_forger', 'epic', false),
  ('title', 'arena_veteran', 'epic', false),
  ('title', 'dragon_slayer', 'legend', false),
  ('title', 'arena_conqueror', 'legend', false),
  ('title', 'legend', 'legend', false),
  ('title', 'aldric_chosen', 'legend', true),
  ('title', 'marchand_reliques', 'rare', true),
  ('title', 'arpenteur_comptoir', 'rare', true),
  ('title', 'tisseur_darics', 'epic', true),
  ('title', 'oeil_aldric', 'epic', true),
  ('title', 'bourse_inepuisable', 'legend', true),
  ('cheat_sheet', 'part5_conjunctions', 'epic', false),
  ('cheat_sheet', 'part3_negation', 'epic', false),
  ('cheat_sheet', 'reading_skim_scan', 'rare', false),
  ('cheat_sheet', 'part5_word_pairs', 'rare', false),
  ('cheat_sheet', 'listening_reductions', 'rare', false),
  ('cheat_sheet', 'part5_modals', 'epic', false),
  ('cheat_sheet', 'business_false_cognates', 'epic', false),
  ('cheat_sheet', 'part7_inference', 'legend', false);
INSERT INTO public.token_catalog (token_type, cap, premium, boost) VALUES
  ('diminishing_bypass', 5, false, false),
  ('streak_shield', 3, false, false),
  ('daily_reroll', 1, false, false),
  ('mock_reset', 2, true, false),
  ('boss_reset', 1, true, false),
  ('endless_resurrect', 2, true, false),
  ('insight_token', 3, true, false),
  ('module_booster', 3, false, true),
  ('mock_multiplier', 2, false, true),
  ('daily_doubler', 2, false, true);
COMMIT;

-- token_cap() lit désormais token_catalog (plus de CASE recopié à la main).
CREATE OR REPLACE FUNCTION public.token_cap(p_type text) RETURNS integer
  LANGUAGE sql STABLE SET search_path = public
AS $function$ SELECT cap FROM token_catalog WHERE token_type = p_type $function$;
REVOKE ALL ON FUNCTION public.token_cap(text) FROM public, anon, authenticated;
